
////////////////////////////////////////////////////////
//                                                    //
// File generated with Hypixel SkyBlock API           //
// Tool by fan87                                      //
// https://github.com/fan87/Hypixel-Skyblock-Remake   //
//                                                    //
// PLEASE CHECK "GENERATOIN" FILE FOR MORE INFO       //
//                                                    //
//                                                    //
////////////////////////////////////////////////////////


package me.fan87.commonplugin.item.init;

import me.fan87.commonplugin.SkyBlock;
import me.fan87.commonplugin.item.SBCustomItem;
import me.fan87.commonplugin.item.SBItems;
import me.fan87.commonplugin.item.impl.ItemVanilla;
import org.bukkit.Material;
import org.bukkit.Color;


// Start class: ItemsHELMET
// Category: HELMET
// Last Update: 2022-01-14 03:34:12.699406

public class ItemsHELMET {

    public static SBCustomItem CRYPT_WITHERLORD_HELMET;
    public static SBCustomItem PERFECT_HELMET_5;
    public static SBCustomItem TITAN_HELMET;
    public static SBCustomItem MAGMA_CUBE_HEAD;
    public static SBCustomItem PERFECT_HELMET_4;
    public static SBCustomItem GROWTH_HELMET;
    public static SBCustomItem KINDRED;
    public static SBCustomItem DEADGEHOG_HELMET;
    public static SBCustomItem SALMON_HAT;
    public static SBCustomItem SQUID_HAT;
    public static SBCustomItem MEGA_LUCK;
    public static SBCustomItem CHICKEN_HEAD;
    public static SBCustomItem WARDEN_HELMET;
    public static SBCustomItem HEAVY_HELMET;
    public static SBCustomItem GOLD_THORN_HEAD;
    public static SBCustomItem SLIME_HAT;
    public static SBCustomItem UNSTABLE_DRAGON_HELMET;
    public static SBCustomItem KRAMPUS_HELMET;
    public static SBCustomItem WITHER_HELMET;
    public static SBCustomItem PROTECTOR_DRAGON_HELMET;
    public static SBCustomItem WEREWOLF_HELMET;
    public static SBCustomItem STARLIGHT_HELMET;
    public static SBCustomItem BLAZE_HELMET;
    public static SBCustomItem PERFECT_HELMET_2;
    public static SBCustomItem SPONGE_HELMET;
    public static SBCustomItem SALMON_HELMET_NEW;
    public static SBCustomItem HEAT_HELMET;
    public static SBCustomItem DIVER_HELMET;
    public static SBCustomItem VAMPIRE_WITCH_MASK;
    public static SBCustomItem DIAMOND_THORN_HEAD;
    public static SBCustomItem ZOMBIE_KNIGHT_HELMET;
    public static SBCustomItem SKELETON_HELMET;
    public static SBCustomItem REVIVED_HEART;
    public static SBCustomItem SKELETON_SOLDIER_HELMET;
    public static SBCustomItem EMPEROR_HEAD;
    public static SBCustomItem SEA_ARCHER_HELMET;
    public static SBCustomItem SUPERIOR_DRAGON_HELMET;
    public static SBCustomItem BLOBFISH_HAT;
    public static SBCustomItem STARRED_ADAPTIVE_HELMET;
    public static SBCustomItem SPEED_WITHER_HELMET;
    public static SBCustomItem PERFECT_HELMET_6;
    public static SBCustomItem SHARK_SCALE_HELMET;
    public static SBCustomItem SKELETON_HAT;
    public static SBCustomItem BOSS;
    public static SBCustomItem FLAMEBREAKER_HELMET;
    public static SBCustomItem DUECES_BUILDER_CLAY;
    public static SBCustomItem GOLD_NECRON_HEAD;
    public static SBCustomItem DCTR_SPACE_HELM;
    public static SBCustomItem CRYSTALLIZED_HEART;
    public static SBCustomItem DARK_GOGGLES;
    public static SBCustomItem PERFECT_HELMET_8;
    public static SBCustomItem FROZEN_BLAZE_HELMET;
    public static SBCustomItem GOLD_PROFESSOR_HEAD;
    public static SBCustomItem DIAMOND_SADAN_HEAD;
    public static SBCustomItem ZOMBIE_HEART;
    public static SBCustomItem ROTTEN_HELMET;
    public static SBCustomItem CREEPER_HAT;
    public static SBCustomItem FINAL_DESTINATION_HELMET;
    public static SBCustomItem TANK_WITHER_HELMET;
    public static SBCustomItem CROWN_OF_GREED;
    public static SBCustomItem NECROMANCER_LORD_HELMET;
    public static SBCustomItem FARM_SUIT_HELMET;
    public static SBCustomItem TANK_MINER_HELMET;
    public static SBCustomItem MASTIFF_HELMET;
    public static SBCustomItem GOLD_BONZO_HEAD;
    public static SBCustomItem HARDENED_DIAMOND_HELMET;
    public static SBCustomItem COW_HEAD;
    public static SBCustomItem LEAFLET_HELMET;
    public static SBCustomItem FISH_HAT;
    public static SBCustomItem MENDER_HELMET;
    public static SBCustomItem SQUIRE_HELMET;
    public static SBCustomItem MENDER_FEDORA;
    public static SBCustomItem ZOMBIE_SOLDIER_HELMET;
    public static SBCustomItem PUMPKIN_HELMET;
    public static SBCustomItem GOLEM_HAT;
    public static SBCustomItem ENDERMAN_HAT;
    public static SBCustomItem GOLEM_ARMOR_HELMET;
    public static SBCustomItem SNIPER_HELMET;
    public static SBCustomItem PIG_MASK;
    public static SBCustomItem SKELETON_MASTER_HELMET;
    public static SBCustomItem BAT_PERSON_HELMET;
    public static SBCustomItem CRYSTAL_HELMET;
    public static SBCustomItem GOLD_SADAN_HEAD;
    public static SBCustomItem WISE_DRAGON_HELMET;
    public static SBCustomItem SPIDER_HAT;
    public static SBCustomItem ADAPTIVE_HELMET;
    public static SBCustomItem ANGLER_HELMET;
    public static SBCustomItem MINOS_HUNTER_HELMET;
    public static SBCustomItem ENCHANTED_JACK_O_LANTERN;
    public static SBCustomItem CACTUS_HELMET;
    public static SBCustomItem FLAME_BREAKER_HELMET;
    public static SBCustomItem SEA_WALKER_HELMET;
    public static SBCustomItem PERFECT_HELMET_7;
    public static SBCustomItem DIAMOND_NECRON_HEAD;
    public static SBCustomItem HELMET_OF_THE_PACK;
    public static SBCustomItem SKELETOR_HELMET;
    public static SBCustomItem GLACITE_HELMET;
    public static SBCustomItem BOUNCY_HELMET;
    public static SBCustomItem PERFECT_HELMET_3;
    public static SBCustomItem FAIRY_HELMET;
    public static SBCustomItem EMERALD_ARMOR_HELMET;
    public static SBCustomItem PERFECT_HELMET_9;
    public static SBCustomItem WATCHER_EYE;
    public static SBCustomItem DIAMOND_BONZO_HEAD;
    public static SBCustomItem ROSETTA_HELMET;
    public static SBCustomItem WITCH_MASK;
    public static SBCustomItem GHAST_HEAD;
    public static SBCustomItem CLOWNFISH_HAT;
    public static SBCustomItem MINERAL_HELMET;
    public static SBCustomItem ARMOR_OF_MAGMA_HELMET;
    public static SBCustomItem SALMON_HELMET;
    public static SBCustomItem STARRED_SHADOW_ASSASSIN_HELMET;
    public static SBCustomItem STRONG_DRAGON_HELMET;
    public static SBCustomItem YOUNG_DRAGON_HELMET;
    public static SBCustomItem SPEED_RACER;
    public static SBCustomItem GOLD_SCARF_HEAD;
    public static SBCustomItem DIAMOND_LIVID_HEAD;
    public static SBCustomItem WITHER_GOGGLES;
    public static SBCustomItem DIAMOND_SCARF_HEAD;
    public static SBCustomItem STARRED_BONZO_MASK;
    public static SBCustomItem SPIRIT_MASK;
    public static SBCustomItem CELESTE_HELMET;
    public static SBCustomItem VAMPIRE_MASK;
    public static SBCustomItem PERFECT_HELMET_11;
    public static SBCustomItem EMBER_HELMET;
    public static SBCustomItem STAR_HELMET;
    public static SBCustomItem BLAZE_HAT;
    public static SBCustomItem MINER_OUTFIT_HELMET;
    public static SBCustomItem ENDERMAN_MASK;
    public static SBCustomItem GOBLIN_HELMET;
    public static SBCustomItem VOODOO;
    public static SBCustomItem RABBIT_HAT;
    public static SBCustomItem PUFFERFISH_HAT;
    public static SBCustomItem SUPER_HEAVY_HELMET;
    public static SBCustomItem POTATO_CROWN;
    public static SBCustomItem GREAT_SPOOK_HELMET;
    public static SBCustomItem SNOW_SUIT_HELMET;
    public static SBCustomItem MENDER_CROWN;
    public static SBCustomItem PERFECT_HELMET_1;
    public static SBCustomItem PERFECT_HELMET_10;
    public static SBCustomItem SKELETON_GRUNT_HELMET;
    public static SBCustomItem DIAMOND_PROFESSOR_HEAD;
    public static SBCustomItem SPOOKY_HELMET;
    public static SBCustomItem FALLEN_STAR_HAT;
    public static SBCustomItem ZOMBIE_LORD_HELMET;
    public static SBCustomItem TARANTULA_HELMET;
    public static SBCustomItem SORROW_HELMET;
    public static SBCustomItem FARM_ARMOR_HELMET;
    public static SBCustomItem WATER_HYDRA_HEAD;
    public static SBCustomItem KALHUIKI_MASK;
    public static SBCustomItem POWER_WITHER_HELMET;
    public static SBCustomItem GENERALS_ARMOR_OF_THE_RESISTANCE_HELMET;
    public static SBCustomItem PERFECT_HELMET_12;
    public static SBCustomItem DIVAN_HELMET;
    public static SBCustomItem BONZO_MASK;
    public static SBCustomItem ZOMBIE_COMMANDER_HELMET;
    public static SBCustomItem ARMOR_OF_YOG_HELMET;
    public static SBCustomItem MUSHROOM_HELMET;
    public static SBCustomItem SHADOW_GOGGLES;
    public static SBCustomItem END_HELMET;
    public static SBCustomItem ARMOR_OF_THE_RESISTANCE_HELMET;
    public static SBCustomItem HOLY_DRAGON_HELMET;
    public static SBCustomItem SKELETON_LORD_HELMET;
    public static SBCustomItem GOLD_LIVID_HEAD;
    public static SBCustomItem ZOMBIE_HAT;
    public static SBCustomItem ANUBIS;
    public static SBCustomItem OLD_DRAGON_HELMET;
    public static SBCustomItem HAPPY_MASK;
    public static SBCustomItem PRECURSOR_EYE;
    public static SBCustomItem LAPIS_ARMOR_HELMET;
    public static SBCustomItem SEA_LANTERN_HAT;
    public static SBCustomItem SPEEDSTER_HELMET;
    public static SBCustomItem MERCENARY_HELMET;
    public static SBCustomItem WISE_WITHER_HELMET;
    public static SBCustomItem REAPER_MASK;
    public static SBCustomItem SHADOW_ASSASSIN_HELMET;



    public ItemsHELMET(SkyBlock skyBlock) {
        CRYPT_WITHERLORD_HELMET = new SBCustomItem("CRYPT_WITHERLORD_HELMET", "Crypt Witherlord Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(69,1,1), SBCustomItem.Category.HELMET, 1, skyBlock);
        SBItems.registerItem(CRYPT_WITHERLORD_HELMET);
        PERFECT_HELMET_5 = new SBCustomItem("PERFECT_HELMET_5", "Perfect Helmet - Tier V", "", Material.DIAMOND_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 2150400, skyBlock);
        SBItems.registerItem(PERFECT_HELMET_5);
        TITAN_HELMET = new SBCustomItem("TITAN_HELMET", "Titan's Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGU4NmUwYjI5M2RlZjVjMjU3MzM4NDNiYmU2Nzc5Y2NkYTc3NTkwZTEzMjI0YTJkYjYyNzZhZDgyM2VkNTVlIn19fQ==", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 50000, skyBlock);
        SBItems.registerItem(TITAN_HELMET);
        MAGMA_CUBE_HEAD = new SBCustomItem("MAGMA_CUBE_HEAD", "Magma Cube Head", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzg5NTdkNTAyM2M5MzdjNGM0MWFhMjQxMmQ0MzQxMGJkYTIzY2Y3OWE5ZjZhYjM2Yjc2ZmVmMmQ3YzQyOSJ9fX0=", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.HELMET, 32, skyBlock);
        SBItems.registerItem(MAGMA_CUBE_HEAD);
        PERFECT_HELMET_4 = new SBCustomItem("PERFECT_HELMET_4", "Perfect Helmet - Tier IV", "", Material.DIAMOND_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 1740800, skyBlock);
        SBItems.registerItem(PERFECT_HELMET_4);
        GROWTH_HELMET = new SBCustomItem("GROWTH_HELMET", "Helmet of Growth", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(0,190,0), SBCustomItem.Category.HELMET, 50000, skyBlock);
        SBItems.registerItem(GROWTH_HELMET);
        KINDRED = new SBCustomItem("KINDRED", "Kindred", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWJiZTcyMWQ3YWQ4YWI5NjVmMDhjYmVjMGI4MzRmNzc5YjUxOTdmNzlkYTRhZWEzZDEzZDI1M2VjZTlkZWMyIn19fQ==", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 1000000, skyBlock);
        SBItems.registerItem(KINDRED);
        DEADGEHOG_HELMET = new SBCustomItem("DEADGEHOG_HELMET", "Deadgehog Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWY1YzVlM2NmNDc5MTJhYmM2YmMyYzk3ZDdiNzM0NzE2NmFlNGFlYWVjOTRlODc1ZjU4NTA0ODYwZDc5M2U5ZiJ9fX0K", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(DEADGEHOG_HELMET);
        SALMON_HAT = new SBCustomItem("SALMON_HAT", "Salmon Hat", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTUwZDEyNTVmNTk3MzZhZTBhNjk0ZWQ1YzkwMDljMWE3MTA3OTMzNTEwYmU0ZWZmYjJiMTUzMjk3ZjUzZjU5NyJ9fX0=", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.HELMET, 40, skyBlock);
        SBItems.registerItem(SALMON_HAT);
        SQUID_HAT = new SBCustomItem("SQUID_HAT", "Squid Hat", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDg3MDU2MjRkYWEyOTU2YWE0NTk1NmM4MWJhYjVmNGZkYjJjNzRhNTk2MDUxZTI0MTkyMDM5YWVhM2E4YjgifX19", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.HELMET, 10, skyBlock);
        SBItems.registerItem(SQUID_HAT);
        MEGA_LUCK = new SBCustomItem("MEGA_LUCK", "Arenjey God", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGRjNWJjZDYzZTRhOTg4MGZjOGQ3OWVjMDlhNjg0MGQzMjczNmM2MDliODlkZmI0Mjc2NTkzODFlZmM2NzU0ZCJ9fX0", SBCustomItem.Rarity.SPECIAL, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(MEGA_LUCK);
        CHICKEN_HEAD = new SBCustomItem("CHICKEN_HEAD", "Chicken Head", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTYzODQ2OWE1OTljZWVmNzIwNzUzNzYwMzI0OGE5YWIxMWZmNTkxZmQzNzhiZWE0NzM1YjM0NmE3ZmFlODkzIn19fQ==", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.HELMET, 8, skyBlock);
        SBItems.registerItem(CHICKEN_HEAD);
        WARDEN_HELMET = new SBCustomItem("WARDEN_HELMET", "Warden Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTVlYjBiZDg1YWFkZGYwZDI5ZWQwODJlYWMwM2ZjYWRlNDNkMGVlODAzYjBlODE2MmFkZDI4YTYzNzlmYjU0ZSJ9fX0=", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(WARDEN_HELMET);
        HEAVY_HELMET = new SBCustomItem("HEAVY_HELMET", "Heavy Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(255,255,255), SBCustomItem.Category.HELMET, 1, skyBlock);
        SBItems.registerItem(HEAVY_HELMET);
        GOLD_THORN_HEAD = new SBCustomItem("GOLD_THORN_HEAD", "Golden Thorn Head", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTU5NTg2MzYzMjU1OCwKICAicHJvZmlsZUlkIiA6ICJhMmY4MzQ1OTVjODk0YTI3YWRkMzA0OTcxNmNhOTEwYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJiUHVuY2giLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTQwMTY4ZTdmN2JjY2QxOWI1YTFlZGU5YTE5NmI0MWM1N2M5MTk4NWVjNzIzYmNmNDIyMDk2NzUyNTU4MjE1OCIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.SPECIAL, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(GOLD_THORN_HEAD);
        SLIME_HAT = new SBCustomItem("SLIME_HAT", "Slime Hat", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTIwZTg0ZDMyZDFlOWM5MTlkM2ZkYmI1M2YyYjM3YmEyNzRjMTIxYzU3YjI4MTBlNWE0NzJmNDBkYWNmMDA0ZiJ9fX0=", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.HELMET, 20, skyBlock);
        SBItems.registerItem(SLIME_HAT);
        UNSTABLE_DRAGON_HELMET = new SBCustomItem("UNSTABLE_DRAGON_HELMET", "Unstable Dragon Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHBzOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzYwNWZjNGUyYjY4YzQ1MDU5YWZlZjM5OTllOWE5NWFhM2Q4OTQzNTk3YTc4OTRlNTY5Mzk3ZDZjZjVkMTY3MmEifX19", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 100000, skyBlock);
        SBItems.registerItem(UNSTABLE_DRAGON_HELMET);
        KRAMPUS_HELMET = new SBCustomItem("KRAMPUS_HELMET", "Krampus Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWYxODk5OGE1MWEyZjI5MTJmMzlhMjk0MjEyYzdlOWQxOTQ3ODlmZTA1M2ZjZjg1MzgyYTllZjIxOWQ5MyJ9fX0=", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(KRAMPUS_HELMET);
        WITHER_HELMET = new SBCustomItem("WITHER_HELMET", "Wither Helmet", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTYwNTU0MzM0ODIwNiwKICAicHJvZmlsZUlkIiA6ICJhMmY4MzQ1OTVjODk0YTI3YWRkMzA0OTcxNmNhOTEwYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJiUHVuY2giLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjkxMTI5NDA5Nzg5NTg5YWUxYjQzZTFkODI4YzA2ZmM5YTIxM2I3ODM0OGE2OGI3MzEzYmRkNDAxZDc0ODVjYyIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 5000, skyBlock);
        SBItems.registerItem(WITHER_HELMET);
        PROTECTOR_DRAGON_HELMET = new SBCustomItem("PROTECTOR_DRAGON_HELMET", "Protector Dragon Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHBzOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzFmMWExY2NiYjAyNGVkMWQyODQ3MWJjNGIzYzI4ZDA5MzI3NzE2MWEzODcxZDI2OTlkNjhlNWQyYzM4Nzk2NCJ9fX0=", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 100000, skyBlock);
        SBItems.registerItem(PROTECTOR_DRAGON_HELMET);
        WEREWOLF_HELMET = new SBCustomItem("WEREWOLF_HELMET", "Werewolf Helmet", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTYwMzY2ODk3MjkwMywKICAicHJvZmlsZUlkIiA6ICIzYTNmNzhkZmExZjQ0OTllYjE5NjlmYzlkOTEwZGYwYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJUaGVyb2Ryb2dvIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2NlNDYwNmM2ZDk3M2E5OTlhZWMxNjg3YzdlMDc1ZjdkMzdkYjgxODVlODhiODQ0NTA3ZjE2YjNlMmIzZWI2OTAiCiAgICB9CiAgfQp9", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 1000, skyBlock);
        SBItems.registerItem(WEREWOLF_HELMET);
        STARLIGHT_HELMET = new SBCustomItem("STARLIGHT_HELMET", "Starlight Helmet", "", Material.GOLD_HELMET, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 17500, skyBlock);
        SBItems.registerItem(STARLIGHT_HELMET);
        BLAZE_HELMET = new SBCustomItem("BLAZE_HELMET", "Blaze Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjk2ZmYxNDVlYTE4ZDYxNjAxNTE4YzY0NmJhZTY3OGY1ZmRlMDk2Y2YwMzYwZWMzNmNhZGFjNDE0MjU1MzRlIn19fQ==", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 576000, skyBlock);
        SBItems.registerItem(BLAZE_HELMET);
        PERFECT_HELMET_2 = new SBCustomItem("PERFECT_HELMET_2", "Perfect Helmet - Tier II", "", Material.DIAMOND_HELMET, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 921600, skyBlock);
        SBItems.registerItem(PERFECT_HELMET_2);
        SPONGE_HELMET = new SBCustomItem("SPONGE_HELMET", "Sponge Helmet", "", Material.SPONGE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 40000, skyBlock);
        SBItems.registerItem(SPONGE_HELMET);
        SALMON_HELMET_NEW = new SBCustomItem("SALMON_HELMET_NEW", "Salmon Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(193,60,15), SBCustomItem.Category.HELMET, 125, skyBlock);
        SBItems.registerItem(SALMON_HELMET_NEW);
        HEAT_HELMET = new SBCustomItem("HEAT_HELMET", "Heat Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(179,179,179), SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(HEAT_HELMET);
        DIVER_HELMET = new SBCustomItem("DIVER_HELMET", "Diver's Mask", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTc4MzBjMWQ4Mjg0NWM5MWI4MzQyOWY5ZGM1OTczMTc4NDE1MzhlMTRkNGZiZWQ2MWFlMWEzYjBlYjdjY2QifX19", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 10000, skyBlock);
        SBItems.registerItem(DIVER_HELMET);
        VAMPIRE_WITCH_MASK = new SBCustomItem("VAMPIRE_WITCH_MASK", "Vampire Witch Mask", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjM0OGU1YjRiM2QyYzFkZWMwMjNmYmY0MDYyMTZmMTIzOTY1ODkwNmVmNGMyZmJmMWM1MzkwNmUyNDNlNjYifX19", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(VAMPIRE_WITCH_MASK);
        DIAMOND_THORN_HEAD = new SBCustomItem("DIAMOND_THORN_HEAD", "Diamond Thorn Head", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTU5NTg2MzY5NTM4NiwKICAicHJvZmlsZUlkIiA6ICJhMmY4MzQ1OTVjODk0YTI3YWRkMzA0OTcxNmNhOTEwYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJiUHVuY2giLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzgzYTFmZmFkY2M2Y2NjNTQ5MDVmMmE3OWI5NjNhMzM5YmI5ZTBiMGJjZWE0MjgyNTJhMTdmMDFlMzE3YmVjMCIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.SPECIAL, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(DIAMOND_THORN_HEAD);
        ZOMBIE_KNIGHT_HELMET = new SBCustomItem("ZOMBIE_KNIGHT_HELMET", "Zombie Knight Helmet", "", Material.GOLD_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 1, skyBlock);
        SBItems.registerItem(ZOMBIE_KNIGHT_HELMET);
        SKELETON_HELMET = new SBCustomItem("SKELETON_HELMET", "Skeleton's Helmet", "", Material.IRON_HELMET, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 51000, skyBlock);
        SBItems.registerItem(SKELETON_HELMET);
        REVIVED_HEART = new SBCustomItem("REVIVED_HEART", "Revived Heart", "", Material.SKULL_ITEM, (short) 3, "eyJ0aW1lc3RhbXAiOjE1NjgzNjYyODI2NDIsInByb2ZpbGVJZCI6IjQxZDNhYmMyZDc0OTQwMGM5MDkwZDU0MzRkMDM4MzFiIiwicHJvZmlsZU5hbWUiOiJNZWdha2xvb24iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzRhNjFiNGY4YjA3MGU0YmMzMGE4NmIyMjkwZGI2ZTU3ZTI2ODFjNDRlMDI1MGQxOTA2YTg5YWRiOGZjNDU1YjEifX19", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(REVIVED_HEART);
        SKELETON_SOLDIER_HELMET = new SBCustomItem("SKELETON_SOLDIER_HELMET", "Skeleton Soldier Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(255,188,11), SBCustomItem.Category.HELMET, 1, skyBlock);
        SBItems.registerItem(SKELETON_SOLDIER_HELMET);
        EMPEROR_HEAD = new SBCustomItem("EMPEROR_HEAD", "Emperor Head", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMDQ0YjY1M2JiYjcyN2I1Yzg2NWE4ZWZjNzUwOTJhZmU5MzllMmMzZTY4NjEzZGI5YWJhZTRmMWI2NGY5OWY4In19fQ==", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(EMPEROR_HEAD);
        SEA_ARCHER_HELMET = new SBCustomItem("SEA_ARCHER_HELMET", "Sea Archer Helmet", "", Material.SKULL_ITEM, (short) 0, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDk4NzFmYmRhODFlNmQ0ZmY2YTVlOGE5Mjk4NWZiNGM3ZTRmYjNkMTRlY2U3NmIwNzc0NGY2NTRhOTU4YjZhMyJ9fX0=", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.HELMET, 50, skyBlock);
        SBItems.registerItem(SEA_ARCHER_HELMET);
        SUPERIOR_DRAGON_HELMET = new SBCustomItem("SUPERIOR_DRAGON_HELMET", "Superior Dragon Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHBzOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzFlMDMyOWY0MjE5MmVlN2MxYTBjNzA0ZjgyZGJiYmU3YzAwZmJmYTNmMDIwYzEwNjdhMjA4NjMwYjk5MWI5ODgifX19", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 100000, skyBlock);
        SBItems.registerItem(SUPERIOR_DRAGON_HELMET);
        BLOBFISH_HAT = new SBCustomItem("BLOBFISH_HAT", "Blobfish Hat", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2EwNjM3Nzc4YmRjYTE4MjRmZjI3NTA2MDNhZWY2MmU5YzkzMTA4OGY0YzdhNTFjMDkwMmVkZDU5NmE3NDZkZSJ9fX0=", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.HELMET, 25, skyBlock);
        SBItems.registerItem(BLOBFISH_HAT);
        STARRED_ADAPTIVE_HELMET = new SBCustomItem("STARRED_ADAPTIVE_HELMET", "Adaptive Helm", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTZmMGQzNGFhYTcxNDM3Nzk4MzcwMWMxYmJlOWIzZjZlN2IzMGNiMzg1NzFiYzBhMmZkNzU0MWQ3ZWRiMTYzNyJ9fX0K", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 20000, skyBlock);
        SBItems.registerItem(STARRED_ADAPTIVE_HELMET);
        SPEED_WITHER_HELMET = new SBCustomItem("SPEED_WITHER_HELMET", "Maxor's Helmet", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTYwNTYyMzMwNDc1OCwKICAicHJvZmlsZUlkIiA6ICI0ZDcwNDg2ZjUwOTI0ZDMzODZiYmZjOWMxMmJhYjRhZSIsCiAgInByb2ZpbGVOYW1lIiA6ICJzaXJGYWJpb3pzY2hlIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2RiZmIwZWQ1OTU5MTkwZDQxNWU3MjZhMTVmMjk4NDAwN2E2N2E1ZmQ0ZWE1NjcxZDBkNjc2ZjlmNjQxYjViYWMiCiAgICB9CiAgfQp9", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(SPEED_WITHER_HELMET);
        PERFECT_HELMET_6 = new SBCustomItem("PERFECT_HELMET_6", "Perfect Helmet - Tier VI", "", Material.DIAMOND_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 2560000, skyBlock);
        SBItems.registerItem(PERFECT_HELMET_6);
        SHARK_SCALE_HELMET = new SBCustomItem("SHARK_SCALE_HELMET", "Shark Scale Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzkwMTE2ZGE1MTRhNzNkZGQ5Mjk1NDkxODUyYWRjNTg4MDA3ZjJhY2Q3ZGUyNjk3ODhhMjEyOGQ4ZTRhNzY0YiJ9fX0=", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 40000, skyBlock);
        SBItems.registerItem(SHARK_SCALE_HELMET);
        SKELETON_HAT = new SBCustomItem("SKELETON_HAT", "Skeleton Hat", "", Material.SKULL_ITEM, (short) 0, "", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.HELMET, 8, skyBlock);
        SBItems.registerItem(SKELETON_HAT);
        BOSS = new SBCustomItem("BOSS", "Boss", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjAyMGMzMzY5MjhkOTRmODhiZmNlYjUxODE4YTY0MDQwYjgyNjZkNDk3ZDM4ZWUxMjhlNDNhNGUwMmUyYTM2In19fQ==", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 1000000, skyBlock);
        SBItems.registerItem(BOSS);
        FLAMEBREAKER_HELMET = new SBCustomItem("FLAMEBREAKER_HELMET", "Ember Ash Helmet", "", Material.CHAINMAIL_HELMET, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(FLAMEBREAKER_HELMET);
        DUECES_BUILDER_CLAY = new SBCustomItem("DUECES_BUILDER_CLAY", "The Builder's Clay", "", Material.STAINED_CLAY, (short) 14, "", SBCustomItem.Rarity.SPECIAL, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(DUECES_BUILDER_CLAY);
        GOLD_NECRON_HEAD = new SBCustomItem("GOLD_NECRON_HEAD", "Golden Necron Head", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTYwNTU1MjgwNDU3MCwKICAicHJvZmlsZUlkIiA6ICJhMmY4MzQ1OTVjODk0YTI3YWRkMzA0OTcxNmNhOTEwYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJiUHVuY2giLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTY2OWUwYjQxZGE0ZmQ1OGY2MjViZmQxNDBiYjViMjRmODRkNTZlZGU2NjU4YjY4ZjEyNDQ3ODA0MmNkYWZlNiIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.SPECIAL, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(GOLD_NECRON_HEAD);
        DCTR_SPACE_HELM = new SBCustomItem("DCTR_SPACE_HELM", "Dctr's Space Helmet", "", Material.STAINED_GLASS, (short) 14, "", SBCustomItem.Rarity.SPECIAL, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(DCTR_SPACE_HELM);
        CRYSTALLIZED_HEART = new SBCustomItem("CRYSTALLIZED_HEART", "Crystallized Heart", "", Material.SKULL_ITEM, (short) 3, "eyJ0aW1lc3RhbXAiOjE1NjgzNTg1OTU4OTEsInByb2ZpbGVJZCI6IjQxZDNhYmMyZDc0OTQwMGM5MDkwZDU0MzRkMDM4MzFiIiwicHJvZmlsZU5hbWUiOiJNZWdha2xvb24iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzg3ZGZiN2MxZWU0ZGUzMWY1NDkzMWVhYzVjNjU3YzE0NWU0ZmE3ZmEwOWUzZjUyYjE3ODhhNjgyYjY1YWM3NSJ9fX0=", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(CRYSTALLIZED_HEART);
        DARK_GOGGLES = new SBCustomItem("DARK_GOGGLES", "Dark Goggles", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjkzMTk1MjU4MjVmMWYzMDcyN2ViOTQwZDNhMDY0MjZiYzRjZWMwN2ZiZDgwYWY1Y2QxNDZlM2ViMzg3OWY2OCJ9fX0K", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 1, skyBlock);
        SBItems.registerItem(DARK_GOGGLES);
        PERFECT_HELMET_8 = new SBCustomItem("PERFECT_HELMET_8", "Perfect Helmet - Tier VIII", "", Material.DIAMOND_HELMET, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 3379200, skyBlock);
        SBItems.registerItem(PERFECT_HELMET_8);
        FROZEN_BLAZE_HELMET = new SBCustomItem("FROZEN_BLAZE_HELMET", "Frozen Blaze Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTVhMTNiYjQ4ZTM1OTViNTVkZThkZDY5NDNmYzM4ZGI1MjM1MzcxMjc4YzY5NWJkNDUzZTQ5YTA5OTkifX19", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 576000, skyBlock);
        SBItems.registerItem(FROZEN_BLAZE_HELMET);
        GOLD_PROFESSOR_HEAD = new SBCustomItem("GOLD_PROFESSOR_HEAD", "Golden Professor Head", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTU5NDQxMDAxNTI3NCwKICAicHJvZmlsZUlkIiA6ICJhMmY4MzQ1OTVjODk0YTI3YWRkMzA0OTcxNmNhOTEwYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJiUHVuY2giLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjhjYTAzZDc4ZDE1N2RmMzRlOGM0Mjg4MWZmNTdlYTg5ODE4MzY3ZTQwZTI4OGRhN2Y4YjQxY2NhNWMxZDQwNiIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.SPECIAL, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(GOLD_PROFESSOR_HEAD);
        DIAMOND_SADAN_HEAD = new SBCustomItem("DIAMOND_SADAN_HEAD", "Diamond Sadan Head", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTYwMTQ3NDUzMzgyMSwKICAicHJvZmlsZUlkIiA6ICJhMmY4MzQ1OTVjODk0YTI3YWRkMzA0OTcxNmNhOTEwYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJiUHVuY2giLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2M2M2M0ZjdmOGY1YjhjNWZlMWJhYzlhNzA4ZTVhNjJjY2QwNDk3MDA3MmFhYjVlMzIzYjFiN2Q0MDA0ZjRhMiIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.SPECIAL, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(DIAMOND_SADAN_HEAD);
        ZOMBIE_HEART = new SBCustomItem("ZOMBIE_HEART", "Zombie's Heart", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzFkN2M4MTZmYzhjNjM2ZDdmNTBhOTNhMGJhN2FhZWZmMDZjOTZhNTYxNjQ1ZTllYjFiZWYzOTE2NTVjNTMxIn19fQ==", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 123000, skyBlock);
        SBItems.registerItem(ZOMBIE_HEART);
        ROTTEN_HELMET = new SBCustomItem("ROTTEN_HELMET", "Rotten Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(158,112,3), SBCustomItem.Category.HELMET, 1, skyBlock);
        SBItems.registerItem(ROTTEN_HELMET);
        CREEPER_HAT = new SBCustomItem("CREEPER_HAT", "Creeper Hat", "", Material.SKULL_ITEM, (short) 4, "", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.HELMET, 16, skyBlock);
        SBItems.registerItem(CREEPER_HAT);
        FINAL_DESTINATION_HELMET = new SBCustomItem("FINAL_DESTINATION_HELMET", "Final Destination Helmet", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTYyMTkyMjk4ODY5MywKICAicHJvZmlsZUlkIiA6ICI0MWQzYWJjMmQ3NDk0MDBjOTA5MGQ1NDM0ZDAzODMxYiIsCiAgInByb2ZpbGVOYW1lIiA6ICJNZWdha2xvb24iLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjIxN2M1NmJiZDc3ZjY0N2I4NDAzODAzZWQ3ZWQ5ODJkZDdhZmNmOGEyY2E0MTMzZDJjMzU3ZWUwODk2ZWZlMiIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(FINAL_DESTINATION_HELMET);
        TANK_WITHER_HELMET = new SBCustomItem("TANK_WITHER_HELMET", "Goldor's Helmet", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTYwNTYyMzIwODgzNSwKICAicHJvZmlsZUlkIiA6ICIyMWUzNjdkNzI1Y2Y0ZTNiYjI2OTJjNGEzMDBhNGRlYiIsCiAgInByb2ZpbGVOYW1lIiA6ICJHZXlzZXJNQyIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kNDkyM2UyOGExODdmZTZhZjIyNzhiNzM5NGVmMjUzYTk2MzMxZmEyZGMwNzMxODc5Yzc4MGJmZWUyNDQyMjhhIgogICAgfQogIH0KfQ", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(TANK_WITHER_HELMET);
        CROWN_OF_GREED = new SBCustomItem("CROWN_OF_GREED", "Crown of Greed", "", Material.GOLD_HELMET, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, true, null, SBCustomItem.Category.HELMET, 1000000, skyBlock);
        SBItems.registerItem(CROWN_OF_GREED);
        NECROMANCER_LORD_HELMET = new SBCustomItem("NECROMANCER_LORD_HELMET", "Necromancer Lord Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODUyZjkyNjk0YWQ4MWU2MzU4YjQzMDcyYWFlZjI1ZjhlMDA5OTE4NGJiNGM3ZmQzODhlNGFkZjcwYWNjN2UwZiJ9fX0", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 5000, skyBlock);
        SBItems.registerItem(NECROMANCER_LORD_HELMET);
        FARM_SUIT_HELMET = new SBCustomItem("FARM_SUIT_HELMET", "Farm Suit Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.COMMON, false, Color.fromRGB(255,255,0), SBCustomItem.Category.HELMET, 25, skyBlock);
        SBItems.registerItem(FARM_SUIT_HELMET);
        TANK_MINER_HELMET = new SBCustomItem("TANK_MINER_HELMET", "Miner Helmet", "", Material.DIAMOND_HELMET, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 2000, skyBlock);
        SBItems.registerItem(TANK_MINER_HELMET);
        MASTIFF_HELMET = new SBCustomItem("MASTIFF_HELMET", "Mastiff Crown", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzI4NTk1MGZkNjc4NThlNzZjNDM5YjBiNWI4N2M2OWE2YzUyYTRkZjkzNmUyMjRkODQzYjE0YzIyNTY1OTQ5ZSJ9fX0=", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(MASTIFF_HELMET);
        GOLD_BONZO_HEAD = new SBCustomItem("GOLD_BONZO_HEAD", "Golden Bonzo Head", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTU5NDQwOTQyNTkyMCwKICAicHJvZmlsZUlkIiA6ICJhMmY4MzQ1OTVjODk0YTI3YWRkMzA0OTcxNmNhOTEwYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJiUHVuY2giLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTVlNzVlYWU4NjliZjBjMjk4ZWU0ODc5MGE2MmMyZDYxNDA3OTBiZDQ4MWIxZGU4OWI3NjhkNTJmMjhjNzRhOSIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.SPECIAL, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(GOLD_BONZO_HEAD);
        HARDENED_DIAMOND_HELMET = new SBCustomItem("HARDENED_DIAMOND_HELMET", "Hardened Diamond Helmet", "", Material.DIAMOND_HELMET, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 3200, skyBlock);
        SBItems.registerItem(HARDENED_DIAMOND_HELMET);
        COW_HEAD = new SBCustomItem("COW_HEAD", "Cow Head", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWQ2YzZlZGE5NDJmN2Y1ZjcxYzMxNjFjNzMwNmY0YWVkMzA3ZDgyODk1ZjlkMmIwN2FiNDUyNTcxOGVkYzUifX19", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.HELMET, 16, skyBlock);
        SBItems.registerItem(COW_HEAD);
        LEAFLET_HELMET = new SBCustomItem("LEAFLET_HELMET", "Leaflet Hat", "", Material.LEAVES, (short) 0, "", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.HELMET, 2, skyBlock);
        SBItems.registerItem(LEAFLET_HELMET);
        FISH_HAT = new SBCustomItem("FISH_HAT", "Fish Hat", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGE3ODZlNGUzNWI1OWQ5MWViNjQ1NGVmMjZiN2IwNjgzNzYxZDZiMTFmMWQ2M2M3NzQwYWYxN2FhM2YifX19", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.HELMET, 24, skyBlock);
        SBItems.registerItem(FISH_HAT);
        MENDER_HELMET = new SBCustomItem("MENDER_HELMET", "Mender Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODc5M2VlZjQ4NDkwNzhkZjRjY2Q0OTgwNTRjNzRlMjE3MWM3NzFmMjczMDk0NDE2NGE4ZWU3YjJkNTYzODMyIn19fQ==", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 1, skyBlock);
        SBItems.registerItem(MENDER_HELMET);
        SQUIRE_HELMET = new SBCustomItem("SQUIRE_HELMET", "Squire Helmet", "", Material.CHAINMAIL_HELMET, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.HELMET, 2500, skyBlock);
        SBItems.registerItem(SQUIRE_HELMET);
        MENDER_FEDORA = new SBCustomItem("MENDER_FEDORA", "Mender Fedora", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTU5NTg2NTE0Njc3MCwKICAicHJvZmlsZUlkIiA6ICI0ZTMwZjUwZTdiYWU0M2YzYWZkMmE3NDUyY2ViZTI5YyIsCiAgInByb2ZpbGVOYW1lIiA6ICJfdG9tYXRvel8iLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWU1OTVlMTQzNDg2YmJkZDk4YjJiNTYyMzAwZDRjNjk4ZTZhNTNhNWFhM2ZhMzI4Zjc0Y2I4MzkwOWUwODhjNCIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(MENDER_FEDORA);
        ZOMBIE_SOLDIER_HELMET = new SBCustomItem("ZOMBIE_SOLDIER_HELMET", "Zombie Soldier Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(208,127,0), SBCustomItem.Category.HELMET, 1, skyBlock);
        SBItems.registerItem(ZOMBIE_SOLDIER_HELMET);
        PUMPKIN_HELMET = new SBCustomItem("PUMPKIN_HELMET", "Pumpkin Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.COMMON, false, Color.fromRGB(237,170,54), SBCustomItem.Category.HELMET, 10, skyBlock);
        SBItems.registerItem(PUMPKIN_HELMET);
        GOLEM_HAT = new SBCustomItem("GOLEM_HAT", "Golem Hat", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODkwOTFkNzllYTBmNTllZjdlZjk0ZDdiYmE2ZTVmMTdmMmY3ZDQ1NzJjNDRmOTBmNzZjNDgxOWE3MTQifX19", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.HELMET, 100, skyBlock);
        SBItems.registerItem(GOLEM_HAT);
        ENDERMAN_HAT = new SBCustomItem("ENDERMAN_HAT", "Enderman Hat", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2E1OWJiMGE3YTMyOTY1YjNkOTBkOGVhZmE4OTlkMTgzNWY0MjQ1MDllYWRkNGU2YjcwOWFkYTUwYjljZiJ9fX0=", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.HELMET, 50, skyBlock);
        SBItems.registerItem(ENDERMAN_HAT);
        GOLEM_ARMOR_HELMET = new SBCustomItem("GOLEM_ARMOR_HELMET", "Golem Armor Helmet", "", Material.IRON_HELMET, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 12000, skyBlock);
        SBItems.registerItem(GOLEM_ARMOR_HELMET);
        SNIPER_HELMET = new SBCustomItem("SNIPER_HELMET", "Sniper Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjE4YzA3MWYwODBkYmE1MGE2MmE2MjYzZmY3MjRlZGMxNTdjZTRmYjQ4ODNjY2VmZjI0OTFkNWJiZGU4MzBjMSJ9fX0K", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 1, skyBlock);
        SBItems.registerItem(SNIPER_HELMET);
        PIG_MASK = new SBCustomItem("PIG_MASK", "Pig Mask", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTYxODQ5OTM0MzY2MiwKICAicHJvZmlsZUlkIiA6ICI0MWQzYWJjMmQ3NDk0MDBjOTA5MGQ1NDM0ZDAzODMxYiIsCiAgInByb2ZpbGVOYW1lIiA6ICJNZWdha2xvb24iLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjUzZjNhMWNlYWUwZjlhOTgzMjBmYTIxYmYyMTYyYzVjZTY5MjkzM2I2MjA1YzQ3Mjg2ZDc4ZGFhMmUyMDczMiIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(PIG_MASK);
        SKELETON_MASTER_HELMET = new SBCustomItem("SKELETON_MASTER_HELMET", "Skeleton Master Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(255,107,11), SBCustomItem.Category.HELMET, 1, skyBlock);
        SBItems.registerItem(SKELETON_MASTER_HELMET);
        BAT_PERSON_HELMET = new SBCustomItem("BAT_PERSON_HELMET", "Bat Person Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTgzYjNmMDRmYzE2YmMyYzJjYjM2YTEyMDQ0MjY1YjBiOTMzZjNkZmEyYjM0MmViNDU3OThmZjdkNzE1YjBkOCJ9fX0=", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(BAT_PERSON_HELMET);
        CRYSTAL_HELMET = new SBCustomItem("CRYSTAL_HELMET", "Crystal Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(252,243,255), SBCustomItem.Category.HELMET, 2500, skyBlock);
        SBItems.registerItem(CRYSTAL_HELMET);
        GOLD_SADAN_HEAD = new SBCustomItem("GOLD_SADAN_HEAD", "Golden Sadan Head", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTYwMTQ3NDQ5NDU3OCwKICAicHJvZmlsZUlkIiA6ICJhMmY4MzQ1OTVjODk0YTI3YWRkMzA0OTcxNmNhOTEwYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJiUHVuY2giLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTc2NmEwZDIxZDI2MWM4Nzg3NjNjYTgyNjRjZDJkZDBiMTdlY2ZhYzM0MjQxMWRiMDc4ODZiMDc4ZTZjYjAxMyIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.SPECIAL, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(GOLD_SADAN_HEAD);
        WISE_DRAGON_HELMET = new SBCustomItem("WISE_DRAGON_HELMET", "Wise Dragon Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHBzOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzU3OTdjNzdjY2VlM2MwNGMzZGVlZDc3MDU5NWVhODNlYTFlODRjOWE0NjI5Yjc1M2FmNWQzNTFjMGNjMTFhNzQifX19", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 100000, skyBlock);
        SBItems.registerItem(WISE_DRAGON_HELMET);
        SPIDER_HAT = new SBCustomItem("SPIDER_HAT", "Spider Hat", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWQ3ZTNiMTlhYzRmM2RlZTljNTY3N2MxMzUzMzNiOWQzNWE3ZjU2OGI2M2QxZWY0YWRhNGIwNjhiNWEyNSJ9fX0=", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.HELMET, 12, skyBlock);
        SBItems.registerItem(SPIDER_HAT);
        ADAPTIVE_HELMET = new SBCustomItem("ADAPTIVE_HELMET", "Adaptive Helm", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTZmMGQzNGFhYTcxNDM3Nzk4MzcwMWMxYmJlOWIzZjZlN2IzMGNiMzg1NzFiYzBhMmZkNzU0MWQ3ZWRiMTYzNyJ9fX0K", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 20000, skyBlock);
        SBItems.registerItem(ADAPTIVE_HELMET);
        ANGLER_HELMET = new SBCustomItem("ANGLER_HELMET", "Angler Helmet", "", Material.DIAMOND_HELMET, (short) 0, "", SBCustomItem.Rarity.COMMON, true, null, SBCustomItem.Category.HELMET, 15, skyBlock);
        SBItems.registerItem(ANGLER_HELMET);
        MINOS_HUNTER_HELMET = new SBCustomItem("MINOS_HUNTER_HELMET", "Minos Hunter Helmet", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTU5ODQzOTU1MzMzMCwKICAicHJvZmlsZUlkIiA6ICI0MWQzYWJjMmQ3NDk0MDBjOTA5MGQ1NDM0ZDAzODMxYiIsCiAgInByb2ZpbGVOYW1lIiA6ICJNZWdha2xvb24iLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGI3MDUwNjg3NDBjZDZiNGMyYjAyNjNkYWVhYjYxMDNkNjUyYjllZmJjYWFkOGFjYmFiZWU2OGU2ZmQxYzRiNCIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.HELMET, 50, skyBlock);
        SBItems.registerItem(MINOS_HUNTER_HELMET);
        ENCHANTED_JACK_O_LANTERN = new SBCustomItem("ENCHANTED_JACK_O_LANTERN", "Lantern Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2NlZDRiY2ZkMjExNjQ2NGRlZGYxNTdiZmM2MmRiMjZjOTU3YTlhNmFjOGJiYzUyNTYzNDY3MDg1YmUyMyJ9fX0=", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.HELMET, 82000, skyBlock);
        SBItems.registerItem(ENCHANTED_JACK_O_LANTERN);
        CACTUS_HELMET = new SBCustomItem("CACTUS_HELMET", "Cactus Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.COMMON, false, Color.fromRGB(0,255,0), SBCustomItem.Category.HELMET, 3, skyBlock);
        SBItems.registerItem(CACTUS_HELMET);
        FLAME_BREAKER_HELMET = new SBCustomItem("FLAME_BREAKER_HELMET", "Flamebreaker Helmet", "", Material.CHAINMAIL_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(FLAME_BREAKER_HELMET);
        SEA_WALKER_HELMET = new SBCustomItem("SEA_WALKER_HELMET", "Sea Walker Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDg4YmE4YmI1MGI3OWU0NDFlNDdiN2U0NTI3NjRkNWZmZjY2OTM3NzlkMmRhZGQ5ZjdmNTJmOThkN2VhMCJ9fX0=", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.HELMET, 50, skyBlock);
        SBItems.registerItem(SEA_WALKER_HELMET);
        PERFECT_HELMET_7 = new SBCustomItem("PERFECT_HELMET_7", "Perfect Helmet - Tier VII", "", Material.DIAMOND_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 2969600, skyBlock);
        SBItems.registerItem(PERFECT_HELMET_7);
        DIAMOND_NECRON_HEAD = new SBCustomItem("DIAMOND_NECRON_HEAD", "Diamond Necron Head", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTYwNTU1MjgyNDM1MiwKICAicHJvZmlsZUlkIiA6ICJhMmY4MzQ1OTVjODk0YTI3YWRkMzA0OTcxNmNhOTEwYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJiUHVuY2giLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGIxMTVjZGM0NWZkODRmMjFmYmE3YWMwZjJiYzc3YmMzYjYzMDJiZTY3MDg0MmY2ZTExZjY2ZWI1NTdmMTNlZSIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.SPECIAL, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(DIAMOND_NECRON_HEAD);
        HELMET_OF_THE_PACK = new SBCustomItem("HELMET_OF_THE_PACK", "Helmet of the Pack", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(255,255,255), SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(HELMET_OF_THE_PACK);
        SKELETOR_HELMET = new SBCustomItem("SKELETOR_HELMET", "Skeletor Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODlkMDc0YWQ5Yjk5NzE4NzllYjMyNWJkZGZmMzY3NWY3MjI0ODU2YmQ2ZDU2OWZjOGQ0ODNjMTMzZDczMDA1ZCJ9fX0K", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 5000, skyBlock);
        SBItems.registerItem(SKELETOR_HELMET);
        GLACITE_HELMET = new SBCustomItem("GLACITE_HELMET", "Glacite Helmet", "", Material.PACKED_ICE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 1750, skyBlock);
        SBItems.registerItem(GLACITE_HELMET);
        BOUNCY_HELMET = new SBCustomItem("BOUNCY_HELMET", "Bouncy Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(173,255,47), SBCustomItem.Category.HELMET, 1, skyBlock);
        SBItems.registerItem(BOUNCY_HELMET);
        PERFECT_HELMET_3 = new SBCustomItem("PERFECT_HELMET_3", "Perfect Helmet - Tier III", "", Material.DIAMOND_HELMET, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 1331200, skyBlock);
        SBItems.registerItem(PERFECT_HELMET_3);
        FAIRY_HELMET = new SBCustomItem("FAIRY_HELMET", "Fairy's Fedora", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(255,51,153), SBCustomItem.Category.HELMET, 420, skyBlock);
        SBItems.registerItem(FAIRY_HELMET);
        EMERALD_ARMOR_HELMET = new SBCustomItem("EMERALD_ARMOR_HELMET", "Emerald Armor Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(0,255,0), SBCustomItem.Category.HELMET, 384000, skyBlock);
        SBItems.registerItem(EMERALD_ARMOR_HELMET);
        PERFECT_HELMET_9 = new SBCustomItem("PERFECT_HELMET_9", "Perfect Helmet - Tier IX", "", Material.DIAMOND_HELMET, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 3788800, skyBlock);
        SBItems.registerItem(PERFECT_HELMET_9);
        WATCHER_EYE = new SBCustomItem("WATCHER_EYE", "Watcher Eye", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGFhOGZjOGRlNjQxN2I0OGQ0OGM4MGI0NDNjZjUzMjZlM2Q5ZGE0ZGJlOWIyNWZjZDQ5NTQ5ZDk2MTY4ZmMwIn19fQ==", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 1, skyBlock);
        SBItems.registerItem(WATCHER_EYE);
        DIAMOND_BONZO_HEAD = new SBCustomItem("DIAMOND_BONZO_HEAD", "Diamond Bonzo Head", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTU5NDQwOTcyODgyOCwKICAicHJvZmlsZUlkIiA6ICJhMmY4MzQ1OTVjODk0YTI3YWRkMzA0OTcxNmNhOTEwYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJiUHVuY2giLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmFlMjAxYjA2ZjEwYjViNGViMDEzMGVjZDdkNTlmYWM3ZTRlMDEzYmJkNGY1ZDVkMDQ2MzU4MGZiMDU0OWE4YiIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.SPECIAL, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(DIAMOND_BONZO_HEAD);
        ROSETTA_HELMET = new SBCustomItem("ROSETTA_HELMET", "Rosetta's Helmet", "", Material.DIAMOND_HELMET, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.HELMET, 525, skyBlock);
        SBItems.registerItem(ROSETTA_HELMET);
        WITCH_MASK = new SBCustomItem("WITCH_MASK", "Witch Mask", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODNiZWU5ZjliNzVmZjc1MTk3ZTA3NDE0YWMyZGI5MmUyMTZlOTQ1ZDYxODc3MjJiZGI5MjYyODc5YmI2In19fQ==", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(WITCH_MASK);
        GHAST_HEAD = new SBCustomItem("GHAST_HEAD", "Ghast Head", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2E4YjcxNGQzMmQ3ZjZjZjhiMzdlMjIxYjc1OGI5YzU5OWZmNzY2NjdjN2NkNDViYmM0OWM1ZWYxOTg1ODY0NiJ9fX0=", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.HELMET, 64, skyBlock);
        SBItems.registerItem(GHAST_HEAD);
        CLOWNFISH_HAT = new SBCustomItem("CLOWNFISH_HAT", "Clownfish Hat", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzZkMTQ5ZTRkNDk5OTI5NjcyZTI3Njg5NDllNjQ3Nzk1OWMyMWU2NTI1NDYxM2IzMjdiNTM4ZGYxZTRkZiJ9fX0=", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.HELMET, 140, skyBlock);
        SBItems.registerItem(CLOWNFISH_HAT);
        MINERAL_HELMET = new SBCustomItem("MINERAL_HELMET", "Mineral Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTI1ZTYxMjE5NzFlOTFjNTQxNWY2MTdlMTcxMTQ5OTBhMTQ2YTc0NmRkOTUyZDQxNzZlMjU3NjQxODNlZiJ9fX0=", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(MINERAL_HELMET);
        ARMOR_OF_MAGMA_HELMET = new SBCustomItem("ARMOR_OF_MAGMA_HELMET", "Armor of Magma Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(255,147,0), SBCustomItem.Category.HELMET, 38000, skyBlock);
        SBItems.registerItem(ARMOR_OF_MAGMA_HELMET);
        SALMON_HELMET = new SBCustomItem("SALMON_HELMET", "Salmon Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(193,60,15), SBCustomItem.Category.HELMET, 125, skyBlock);
        SBItems.registerItem(SALMON_HELMET);
        STARRED_SHADOW_ASSASSIN_HELMET = new SBCustomItem("STARRED_SHADOW_ASSASSIN_HELMET", "Shadow Assassin Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWI4YWY1MmVmMmY3MmMzYmY1ZWNlNmU3MGE4MmYxMzcxOTU5Y2UzZmNiNzM2YzUwMDMwNWNhZGRjNTA1YzVlMiJ9fX0", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 5000, skyBlock);
        SBItems.registerItem(STARRED_SHADOW_ASSASSIN_HELMET);
        STRONG_DRAGON_HELMET = new SBCustomItem("STRONG_DRAGON_HELMET", "Strong Dragon Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHBzOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzc4YmM2NTUxYmViMjE0OGQ5MzliNjk5MjUxNDBkMjM3OWZlMGZhYjZlN2QzMWY2NWRmNTBiNTllOWY3N2EwZTQifX19", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 100000, skyBlock);
        SBItems.registerItem(STRONG_DRAGON_HELMET);
        YOUNG_DRAGON_HELMET = new SBCustomItem("YOUNG_DRAGON_HELMET", "Young Dragon Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHBzOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2EwZTgxZWQwN2RmYjAyNDRkNTZmNGQ1ZjJiMzc1NTNlYzAyNmZiNDc5NmYwZmIwYzU3YThlYjI2NDk4M2UxZTAifX19", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 100000, skyBlock);
        SBItems.registerItem(YOUNG_DRAGON_HELMET);
        SPEED_RACER = new SBCustomItem("SPEED_RACER", "The Fast", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2QxNGUyNTJjYTRhMzQzODgyYzNiMDViYmNmYjhmYzgzN2QyZGU5ZGI0MWRjNTM3MTEzYjczMjA5OCJ9fX0=", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(SPEED_RACER);
        GOLD_SCARF_HEAD = new SBCustomItem("GOLD_SCARF_HEAD", "Golden Scarf Head", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTU5NDQwOTkwNTg0MiwKICAicHJvZmlsZUlkIiA6ICJhMmY4MzQ1OTVjODk0YTI3YWRkMzA0OTcxNmNhOTEwYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJiUHVuY2giLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjEyZjkwYTJhNjZkN2Y5MzdjZjlmYjE1YzdkOGFlZjk3ZDM4ZjU2MmJkOTY3OGIyNGY0YzkwNGI2NWJjYzYwYyIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.SPECIAL, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(GOLD_SCARF_HEAD);
        DIAMOND_LIVID_HEAD = new SBCustomItem("DIAMOND_LIVID_HEAD", "Diamond Livid Head", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTYwMDI2ODc3ODYyMSwKICAicHJvZmlsZUlkIiA6ICJhMmY4MzQ1OTVjODk0YTI3YWRkMzA0OTcxNmNhOTEwYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJiUHVuY2giLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTI2OGUzNjUwNWYxMzEyMzg0ZWIzNmVkNDc3ZjRjMjA1MzU3NmM2MDA1OGZkMjZiZWRlMjRkOTBjYjRjZjdiZiIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.SPECIAL, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(DIAMOND_LIVID_HEAD);
        WITHER_GOGGLES = new SBCustomItem("WITHER_GOGGLES", "Wither Goggles", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTYwNTU0MzM0MTg4MSwKICAicHJvZmlsZUlkIiA6ICJiMGQ0YjI4YmMxZDc0ODg5YWYwZTg2NjFjZWU5NmFhYiIsCiAgInByb2ZpbGVOYW1lIiA6ICJNaW5lU2tpbl9vcmciLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzdjZWI4ZjA3NThlMmQ4YWM0OWRlNmY5Nzc2MDNjN2JmYzIzZmQ4MmE4NTc0ODEwYTQ1ZjVlOTdjNjQzNmQ3OSIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(WITHER_GOGGLES);
        DIAMOND_SCARF_HEAD = new SBCustomItem("DIAMOND_SCARF_HEAD", "Diamond Scarf Head", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTU5NDQwOTk3NjM1MSwKICAicHJvZmlsZUlkIiA6ICJhMmY4MzQ1OTVjODk0YTI3YWRkMzA0OTcxNmNhOTEwYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJiUHVuY2giLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGRhNWNhMmY2ODAwNTE2YTYzZDI1ODc4ZWI3YTcxM2U4MGQ2M2I2MmY5ZjZjYWIzZjMxMDk3Zjk0OTRiNjEyMSIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.SPECIAL, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(DIAMOND_SCARF_HEAD);
        STARRED_BONZO_MASK = new SBCustomItem("STARRED_BONZO_MASK", "Bonzo's Mask", "", Material.SKULL_ITEM, (short) 3, "eyJ0aW1lc3RhbXAiOjE1NzQ0MTkzMTAxNjQsInByb2ZpbGVJZCI6Ijc1MTQ0NDgxOTFlNjQ1NDY4Yzk3MzlhNmUzOTU3YmViIiwicHJvZmlsZU5hbWUiOiJUaGFua3NNb2phbmciLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzEyNzE2ZWNiZjViOGRhMDBiMDVmMzE2ZWM2YWY2MWU4YmQwMjgwNWIyMWViOGU0NDAxNTE0NjhkYzY1NjU0OWMifX19", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(STARRED_BONZO_MASK);
        SPIRIT_MASK = new SBCustomItem("SPIRIT_MASK", "Spirit Mask", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWJiZTcyMWQ3YWQ4YWI5NjVmMDhjYmVjMGI4MzRmNzc5YjUxOTdmNzlkYTRhZWEzZDEzZDI1M2VjZTlkZWMyIn19fQ==", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 20000, skyBlock);
        SBItems.registerItem(SPIRIT_MASK);
        CELESTE_HELMET = new SBCustomItem("CELESTE_HELMET", "Celeste Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, Color.fromRGB(212,142,242), SBCustomItem.Category.HELMET, 2500, skyBlock);
        SBItems.registerItem(CELESTE_HELMET);
        VAMPIRE_MASK = new SBCustomItem("VAMPIRE_MASK", "Vampire Mask", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGQ0NDc1NmUwYjRlY2U4ZDc0NjI5NmEzZDVlMjk3ZTE0MTVmNGJhMTc2NDdmZmUyMjgzODUzODNkMTYxYTkifX19", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 10, skyBlock);
        SBItems.registerItem(VAMPIRE_MASK);
        PERFECT_HELMET_11 = new SBCustomItem("PERFECT_HELMET_11", "Perfect Helmet - Tier XI", "", Material.DIAMOND_HELMET, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 4608000, skyBlock);
        SBItems.registerItem(PERFECT_HELMET_11);
        EMBER_HELMET = new SBCustomItem("EMBER_HELMET", "Ember Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzhkMTk5ZTIzYzE3NDg4YTAxYTA3MDA1YTQxZmUzMzBiMWQyMmIwNGU5OTk0M2M5ZjhjODk3ZDE1NmU5NTU1YSJ9fX0=", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 1000, skyBlock);
        SBItems.registerItem(EMBER_HELMET);
        STAR_HELMET = new SBCustomItem("STAR_HELMET", "Helmet of the Stars", "", Material.GOLD_HELMET, (short) 0, "", SBCustomItem.Rarity.SPECIAL, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(STAR_HELMET);
        BLAZE_HAT = new SBCustomItem("BLAZE_HAT", "Blaze Hat", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjc4ZWYyZTRjZjJjNDFhMmQxNGJmZGU5Y2FmZjEwMjE5ZjViMWJmNWIzNWE0OWViNTFjNjQ2Nzg4MmNiNWYwIn19fQ==", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.HELMET, 20, skyBlock);
        SBItems.registerItem(BLAZE_HAT);
        MINER_OUTFIT_HELMET = new SBCustomItem("MINER_OUTFIT_HELMET", "Miner's Outfit Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, Color.fromRGB(122,121,100), SBCustomItem.Category.HELMET, 400, skyBlock);
        SBItems.registerItem(MINER_OUTFIT_HELMET);
        ENDERMAN_MASK = new SBCustomItem("ENDERMAN_MASK", "Enderman Mask", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDc0NmMyNmFhYzE2ZTM4ODA5ODJkMTM5OWZiNWY5Zjc5OTEzZGQ2MTZlNzE2NTRmOWJmNGQ0MWZiMzMifX19", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.HELMET, 10, skyBlock);
        SBItems.registerItem(ENDERMAN_MASK);
        GOBLIN_HELMET = new SBCustomItem("GOBLIN_HELMET", "Goblin Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGJmNTZjNjU0MWMxMjY2ZmZjNDYzNTEwYmRiNTVhZWY5MzE1YWY1NDg4OThjZjVkM2NiYTFiNWI0YzAxIn19fQ", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 1500, skyBlock);
        SBItems.registerItem(GOBLIN_HELMET);
        VOODOO = new SBCustomItem("VOODOO", "Voodoo", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTcwODI1ZjNjMDJlYjNkM2Y4ZDEzMTIzYjYyNDkxMWM4YTU3ZDk3OTU1ZjNlYTcxNmFjYzIxMjcxNDQ1MDMyMyJ9fX0=", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 1000000, skyBlock);
        SBItems.registerItem(VOODOO);
        RABBIT_HAT = new SBCustomItem("RABBIT_HAT", "Rabbit Hat", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWY1OTg1MWRlOTNmNGM2NTQ3ZjgwOWNhM2FlZDE4OWU5NGJiZjRmODg4ZjFmNzUyMDhlOTRjMzczMzg1MmExIn19fQ==", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.HELMET, 10, skyBlock);
        SBItems.registerItem(RABBIT_HAT);
        PUFFERFISH_HAT = new SBCustomItem("PUFFERFISH_HAT", "Pufferfish Hat", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTk1NTkzODg5OTNmZTc4MmY2N2JkNThkOThjNGRmNTZiY2Q0MzBlZGNiMmY2NmVmNTc3N2E3M2MyN2RlMyJ9fX0=", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.HELMET, 60, skyBlock);
        SBItems.registerItem(PUFFERFISH_HAT);
        SUPER_HEAVY_HELMET = new SBCustomItem("SUPER_HEAVY_HELMET", "Super Heavy Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(230,230,230), SBCustomItem.Category.HELMET, 1, skyBlock);
        SBItems.registerItem(SUPER_HEAVY_HELMET);
        POTATO_CROWN = new SBCustomItem("POTATO_CROWN", "Potato Crown", "", Material.GOLD_HELMET, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(POTATO_CROWN);
        GREAT_SPOOK_HELMET = new SBCustomItem("GREAT_SPOOK_HELMET", "Great Spook Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(153,51,153), SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(GREAT_SPOOK_HELMET);
        SNOW_SUIT_HELMET = new SBCustomItem("SNOW_SUIT_HELMET", "Snow Suit Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2QxMTE5NjQzY2VjZmJlMDA0MTQxYTFlYTQwNjJmODMxNWNhNzhlNTAzOTU4YWM1MDUwNWU4NTkyYzQ0YTYwMSJ9fX0=", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 1000, skyBlock);
        SBItems.registerItem(SNOW_SUIT_HELMET);
        MENDER_CROWN = new SBCustomItem("MENDER_CROWN", "Mender Crown", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTYwNTU0MzQwNjU0NSwKICAicHJvZmlsZUlkIiA6ICI5NGMzZGM3YTdiMmQ0NzQ1YmVlYjQzZDc2ZjRjNDVkYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJEb25fVml0b0Nvcmxlb25lIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2EzMDY1ZDUwNDk1YzBhMmYyNWEzM2Y5MmFhOTBkMDg0OWNhZjkxNDcwYmIxMDI3ZDdmNzljZGI1Y2UzNzM4ZWMiCiAgICB9CiAgfQp9", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(MENDER_CROWN);
        PERFECT_HELMET_1 = new SBCustomItem("PERFECT_HELMET_1", "Perfect Helmet - Tier I", "", Material.DIAMOND_HELMET, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 512000, skyBlock);
        SBItems.registerItem(PERFECT_HELMET_1);
        PERFECT_HELMET_10 = new SBCustomItem("PERFECT_HELMET_10", "Perfect Helmet - Tier X", "", Material.DIAMOND_HELMET, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 4198400, skyBlock);
        SBItems.registerItem(PERFECT_HELMET_10);
        SKELETON_GRUNT_HELMET = new SBCustomItem("SKELETON_GRUNT_HELMET", "Skeleton Grunt Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(225,235,52), SBCustomItem.Category.HELMET, 1, skyBlock);
        SBItems.registerItem(SKELETON_GRUNT_HELMET);
        DIAMOND_PROFESSOR_HEAD = new SBCustomItem("DIAMOND_PROFESSOR_HEAD", "Diamond Professor Head", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTU5NDQxMDA2NTE1MiwKICAicHJvZmlsZUlkIiA6ICJhMmY4MzQ1OTVjODk0YTI3YWRkMzA0OTcxNmNhOTEwYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJiUHVuY2giLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjIzYzNhZDhjNDQxMDE0NTA5NTI4MDc3OTI5M2NjMWU3OTA0YjZmY2U5M2Q3MDM3OGFjNWYzMjAzMmJhMWQ4NiIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.SPECIAL, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(DIAMOND_PROFESSOR_HEAD);
        SPOOKY_HELMET = new SBCustomItem("SPOOKY_HELMET", "Spooky Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGM2NTcwZjEyNDI5OTJmNmViYTIzZWU1ODI1OThjMzllM2U3NDUzODMyNzNkZWVmOGIzOTc3NTgzZmUzY2Y1In19fQ==", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(SPOOKY_HELMET);
        FALLEN_STAR_HAT = new SBCustomItem("FALLEN_STAR_HAT", "Fallen Star Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzc2NWEwNTQ4YTA0ZmIyMjE1MGQzMTg5ZDdjZGI2OTgyYzEzZDc4NjBlMzIzNjY0NTVkMDU0NTc1MTY0ZTcwMSJ9fX0", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 500, skyBlock);
        SBItems.registerItem(FALLEN_STAR_HAT);
        ZOMBIE_LORD_HELMET = new SBCustomItem("ZOMBIE_LORD_HELMET", "Zombie Lord Helmet", "", Material.GOLD_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 1, skyBlock);
        SBItems.registerItem(ZOMBIE_LORD_HELMET);
        TARANTULA_HELMET = new SBCustomItem("TARANTULA_HELMET", "Tarantula Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(0,0,0), SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(TARANTULA_HELMET);
        SORROW_HELMET = new SBCustomItem("SORROW_HELMET", "Sorrow Helmet", "", Material.CHAINMAIL_HELMET, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 75000, skyBlock);
        SBItems.registerItem(SORROW_HELMET);
        FARM_ARMOR_HELMET = new SBCustomItem("FARM_ARMOR_HELMET", "Farm Armor Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(255,215,0), SBCustomItem.Category.HELMET, 3200, skyBlock);
        SBItems.registerItem(FARM_ARMOR_HELMET);
        WATER_HYDRA_HEAD = new SBCustomItem("WATER_HYDRA_HEAD", "Water Hydra Head", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjFmZmJkYTkyNDQyODczZDU0MDUxZTRlMTdlYTQ3Mjc4Y2IzYjc0N2Q3OTgwNzBiYTgzYmM0YTlkZTU4ZGQifX19", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 500, skyBlock);
        SBItems.registerItem(WATER_HYDRA_HEAD);
        KALHUIKI_MASK = new SBCustomItem("KALHUIKI_MASK", "Kalhuiki Mask", "§7A ceremonial mask worn by the members of the Kalhuiki Tribe.", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTYxOTE4MzY4ODY1MSwKICAicHJvZmlsZUlkIiA6ICI3MzgyZGRmYmU0ODU0NTVjODI1ZjkwMGY4OGZkMzJmOCIsCiAgInByb2ZpbGVOYW1lIiA6ICJJb3lhbCIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kNjU4NzA2MTliMGMyZGI4MjI0NzlkMmNiMzgyMTI2YmQ3OTljNTgyMzc4YjViMWRmOTNlNzViN2QwMTU1MWI3IgogICAgfQogIH0KfQ==", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(KALHUIKI_MASK);
        POWER_WITHER_HELMET = new SBCustomItem("POWER_WITHER_HELMET", "Necron's Helmet", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTYwNTYyMzI0OTc5MywKICAicHJvZmlsZUlkIiA6ICIwNjEzY2I1Y2QxYjg0M2JjYjI4OTk1NWU4N2QzMGEyYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJicmVhZGxvYWZzcyIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yYmJiMmZhN2E2Y2EwODcyODBlYTBjYjU2NGI0MWVmMWFlNDA0YTE5ZjdhODEyOGQzZDI4YzUxOWE4NWUwNjNmIgogICAgfQogIH0KfQ", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 5000, skyBlock);
        SBItems.registerItem(POWER_WITHER_HELMET);
        GENERALS_ARMOR_OF_THE_RESISTANCE_HELMET = new SBCustomItem("GENERALS_ARMOR_OF_THE_RESISTANCE_HELMET", "Helmet of the Rising Sun", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTYxODIzMzEwNTIyOSwKICAicHJvZmlsZUlkIiA6ICIzYTNmNzhkZmExZjQ0OTllYjE5NjlmYzlkOTEwZGYwYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJOb19jcmVyYXIiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzRjZjNjNWYyNGM5YmY4YjkwMzFlOGFlZDUzMzdiNmEwN2Y4MTljZGU4YzYyMjA4NTU0NTE2MmY4YTY5MzA2MCIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9CiAgfQp9", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 10, skyBlock);
        SBItems.registerItem(GENERALS_ARMOR_OF_THE_RESISTANCE_HELMET);
        PERFECT_HELMET_12 = new SBCustomItem("PERFECT_HELMET_12", "Perfect Helmet - Tier XII", "", Material.DIAMOND_HELMET, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 5017600, skyBlock);
        SBItems.registerItem(PERFECT_HELMET_12);
        DIVAN_HELMET = new SBCustomItem("DIVAN_HELMET", "Helmet Of Divan", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODNmNjllZjI3ZjMxMjBhNTEwNTBlNmJlNjZhMGUzZjhlODlhZjg4OGQ0ODA2NzE2YmY4NmY1OTBkYTYzODMxNyJ9fX0=", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(DIVAN_HELMET);
        BONZO_MASK = new SBCustomItem("BONZO_MASK", "Bonzo's Mask", "", Material.SKULL_ITEM, (short) 3, "eyJ0aW1lc3RhbXAiOjE1NzQ0MTkzMTAxNjQsInByb2ZpbGVJZCI6Ijc1MTQ0NDgxOTFlNjQ1NDY4Yzk3MzlhNmUzOTU3YmViIiwicHJvZmlsZU5hbWUiOiJUaGFua3NNb2phbmciLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzEyNzE2ZWNiZjViOGRhMDBiMDVmMzE2ZWM2YWY2MWU4YmQwMjgwNWIyMWViOGU0NDAxNTE0NjhkYzY1NjU0OWMifX19", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(BONZO_MASK);
        ZOMBIE_COMMANDER_HELMET = new SBCustomItem("ZOMBIE_COMMANDER_HELMET", "Zombie Commander Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(213,18,48), SBCustomItem.Category.HELMET, 1, skyBlock);
        SBItems.registerItem(ZOMBIE_COMMANDER_HELMET);
        ARMOR_OF_YOG_HELMET = new SBCustomItem("ARMOR_OF_YOG_HELMET", "Yog Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(200,50,0), SBCustomItem.Category.HELMET, 38000, skyBlock);
        SBItems.registerItem(ARMOR_OF_YOG_HELMET);
        MUSHROOM_HELMET = new SBCustomItem("MUSHROOM_HELMET", "Mushroom Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.COMMON, false, Color.fromRGB(255,0,0), SBCustomItem.Category.HELMET, 10, skyBlock);
        SBItems.registerItem(MUSHROOM_HELMET);
        SHADOW_GOGGLES = new SBCustomItem("SHADOW_GOGGLES", "Shadow Goggles", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTU5NTg2NTE2MjgwMiwKICAicHJvZmlsZUlkIiA6ICI3MzgyZGRmYmU0ODU0NTVjODI1ZjkwMGY4OGZkMzJmOCIsCiAgInByb2ZpbGVOYW1lIiA6ICJ4cWwiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzQ2NWE4NDdlMTE0ZWY2MmU3ODMzY2JmYjJmZTVkZTU3NjRiYWI1ZjEwYWYxMjVmZDJkMzE2MjM4MjY4Mjc5ZiIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(SHADOW_GOGGLES);
        END_HELMET = new SBCustomItem("END_HELMET", "Ender Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjcxNWNhMGY3NDI1NDRhZTNjYTEwNDI5NzU3OGMyZWQ3MDBlYTNhNTQ5ODA0MTM1MTJmNWU3YTBiYzA2NzI5YSJ9fX0=", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 10000, skyBlock);
        SBItems.registerItem(END_HELMET);
        ARMOR_OF_THE_RESISTANCE_HELMET = new SBCustomItem("ARMOR_OF_THE_RESISTANCE_HELMET", "Helmet of the Rising Sun", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTYxODIzMzEwNTIyOSwKICAicHJvZmlsZUlkIiA6ICIzYTNmNzhkZmExZjQ0OTllYjE5NjlmYzlkOTEwZGYwYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJOb19jcmVyYXIiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzRjZjNjNWYyNGM5YmY4YjkwMzFlOGFlZDUzMzdiNmEwN2Y4MTljZGU4YzYyMjA4NTU0NTE2MmY4YTY5MzA2MCIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9CiAgfQp9", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 10, skyBlock);
        SBItems.registerItem(ARMOR_OF_THE_RESISTANCE_HELMET);
        HOLY_DRAGON_HELMET = new SBCustomItem("HOLY_DRAGON_HELMET", "Holy Dragon Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTljYzhiYTI2NzkzMjE4ZjZmNjQ5MTk0N2ExODM3ZmQ1Mjg3ODcwMWYzM2Y3NmJiZTI4ODNhNDVhYmE4YWI4ZiJ9fX0K", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 100000, skyBlock);
        SBItems.registerItem(HOLY_DRAGON_HELMET);
        SKELETON_LORD_HELMET = new SBCustomItem("SKELETON_LORD_HELMET", "Skeleton Lord Helmet", "", Material.GOLD_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 1, skyBlock);
        SBItems.registerItem(SKELETON_LORD_HELMET);
        GOLD_LIVID_HEAD = new SBCustomItem("GOLD_LIVID_HEAD", "Golden Livid Head", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTYwMDI2ODczMjkyNSwKICAicHJvZmlsZUlkIiA6ICJhMmY4MzQ1OTVjODk0YTI3YWRkMzA0OTcxNmNhOTEwYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJiUHVuY2giLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjI1MTJhYzZjYzVkOGM3YWUzZGRkZWVlMmM0MjlkNGEyZDZhODM0MWJkZTA1NmUxOGU1YWUyMTAxMWJiZTY0MyIKICAgIH0KICB9Cn0=", SBCustomItem.Rarity.SPECIAL, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(GOLD_LIVID_HEAD);
        ZOMBIE_HAT = new SBCustomItem("ZOMBIE_HAT", "Zombie Hat", "", Material.SKULL_ITEM, (short) 2, "", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.HELMET, 8, skyBlock);
        SBItems.registerItem(ZOMBIE_HAT);
        ANUBIS = new SBCustomItem("ANUBIS", "Anubis", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGNhNjlmY2VlOGFlOWE5Mzg0NTMzZWI5NWY2NDQ3NGJlNTA1OTEwZDk1OWZmNGFjMTI2MTFiMzAxN2UwNzlkMCJ9fX0=", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 1000000, skyBlock);
        SBItems.registerItem(ANUBIS);
        OLD_DRAGON_HELMET = new SBCustomItem("OLD_DRAGON_HELMET", "Old Dragon Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHBzOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzUyNGM0ZGE2YWIyN2U5YzkzZmJmNDllYTFiMWZlZmFlZmJlMmQ0YzBjOGIyMjJlMmZmNmIxODE3OWZiNWFkZGYifX19", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 100000, skyBlock);
        SBItems.registerItem(OLD_DRAGON_HELMET);
        HAPPY_MASK = new SBCustomItem("HAPPY_MASK", "Happy Mask", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQwYjE2YzEyM2UyMWE3ZDE5ZTZjYTI5NDBlNWY1YzNkYjlmNjM4ZDYzMTc4NWZlOWRmNTU0ZWQ2NzQ0MWM0ZiJ9fX0K", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(HAPPY_MASK);
        PRECURSOR_EYE = new SBCustomItem("PRECURSOR_EYE", "Precursor Eye", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTYwMTQ3OTI0MjkyNCwKICAicHJvZmlsZUlkIiA6ICI1NjY3NWIyMjMyZjA0ZWUwODkxNzllOWM5MjA2Y2ZlOCIsCiAgInByb2ZpbGVOYW1lIiA6ICJUaGVJbmRyYSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83MmMwNjgzYjIwMTljYTNkMzk0NzI3M2UzOTRiZmNhMWI0ZDcxYjYxYjY3YjM5NDc0YzJkNmQ3M2E5YjY3NTA4IgogICAgfQogIH0KfQ==", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 1000, skyBlock);
        SBItems.registerItem(PRECURSOR_EYE);
        LAPIS_ARMOR_HELMET = new SBCustomItem("LAPIS_ARMOR_HELMET", "Lapis Armor Helmet", "", Material.SEA_LANTERN, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.HELMET, 1000, skyBlock);
        SBItems.registerItem(LAPIS_ARMOR_HELMET);
        SEA_LANTERN_HAT = new SBCustomItem("SEA_LANTERN_HAT", "Sea Lantern Hat", "", Material.SEA_LANTERN, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(SEA_LANTERN_HAT);
        SPEEDSTER_HELMET = new SBCustomItem("SPEEDSTER_HELMET", "Speedster Helmet", "", Material.LEATHER_HELMET, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(224,252,247), SBCustomItem.Category.HELMET, 128000, skyBlock);
        SBItems.registerItem(SPEEDSTER_HELMET);
        MERCENARY_HELMET = new SBCustomItem("MERCENARY_HELMET", "Mercenary Helmet", "", Material.IRON_HELMET, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.HELMET, 10000, skyBlock);
        SBItems.registerItem(MERCENARY_HELMET);
        WISE_WITHER_HELMET = new SBCustomItem("WISE_WITHER_HELMET", "Storm's Helmet", "", Material.SKULL_ITEM, (short) 3, "ewogICJ0aW1lc3RhbXAiIDogMTYwNTYyMzM2NjgxNiwKICAicHJvZmlsZUlkIiA6ICI5MWYwNGZlOTBmMzY0M2I1OGYyMGUzMzc1Zjg2ZDM5ZSIsCiAgInByb2ZpbGVOYW1lIiA6ICJTdG9ybVN0b3JteSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mODMxNTljNWJiN2Q4MDQ1NGQyZDY0NmIxNTc3NGI3MTE2YWFiY2IzYWY1YjY3NzdhMjc1NzNmYzQ1Zjc4NTRmIgogICAgfQogIH0KfQ", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 5000, skyBlock);
        SBItems.registerItem(WISE_WITHER_HELMET);
        REAPER_MASK = new SBCustomItem("REAPER_MASK", "Reaper Mask", "", Material.SKULL_ITEM, (short) 3, "eyJ0aW1lc3RhbXAiOjE1NjgwMzY3MjYwNjYsInByb2ZpbGVJZCI6IjQxZDNhYmMyZDc0OTQwMGM5MDkwZDU0MzRkMDM4MzFiIiwicHJvZmlsZU5hbWUiOiJNZWdha2xvb24iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzFmYzAxODQ0NzNmZTg4MmQyODk1Y2U3Y2JjODE5N2JkNDBmZjcwYmYxMGQzNzQ1ZGU5N2I2YzJhOWM1ZmM3OGYifX19", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.HELMET, 0, skyBlock);
        SBItems.registerItem(REAPER_MASK);
        SHADOW_ASSASSIN_HELMET = new SBCustomItem("SHADOW_ASSASSIN_HELMET", "Shadow Assassin Helmet", "", Material.SKULL_ITEM, (short) 3, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWI4YWY1MmVmMmY3MmMzYmY1ZWNlNmU3MGE4MmYxMzcxOTU5Y2UzZmNiNzM2YzUwMDMwNWNhZGRjNTA1YzVlMiJ9fX0", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.HELMET, 5000, skyBlock);
        SBItems.registerItem(SHADOW_ASSASSIN_HELMET);


    }

}

