
////////////////////////////////////////////////////////
//                                                    //
// File generated with Hypixel SkyBlock API           //
// Tool by fan87                                      //
// https://github.com/fan87/Hypixel-Skyblock-Remake   //
//                                                    //
// PLEASE CHECK "GENERATOIN" FILE FOR MORE INFO       //
//                                                    //
//                                                    //
////////////////////////////////////////////////////////


package me.fan87.commonplugin.item.init;

import me.fan87.commonplugin.SkyBlock;
import me.fan87.commonplugin.item.SBCustomItem;
import me.fan87.commonplugin.item.SBItems;
import me.fan87.commonplugin.item.impl.ItemVanilla;
import org.bukkit.Material;
import org.bukkit.Color;


// Start class: ItemsBOOTS
// Category: BOOTS
// Last Update: 2022-01-10 17:27:50.173370

public class ItemsBOOTS {

    public static SBCustomItem SHADOW_ASSASSIN_BOOTS;
    public static SBCustomItem OLD_DRAGON_BOOTS;
    public static SBCustomItem UNSTABLE_DRAGON_BOOTS;
    public static SBCustomItem SKELETON_MASTER_BOOTS;
    public static SBCustomItem SQUIRE_BOOTS;
    public static SBCustomItem DIVER_BOOTS;
    public static SBCustomItem WISE_DRAGON_BOOTS;
    public static SBCustomItem THORNS_BOOTS;
    public static SBCustomItem POWER_WITHER_BOOTS;
    public static SBCustomItem DIVAN_BOOTS;
    public static SBCustomItem CELESTE_BOOTS;
    public static SBCustomItem ZOMBIE_BOOTS;
    public static SBCustomItem SKELETON_GRUNT_BOOTS;
    public static SBCustomItem DASHING_BOOTS;
    public static SBCustomItem SUPER_HEAVY_BOOTS;
    public static SBCustomItem REAPER_BOOTS;
    public static SBCustomItem ARMOR_OF_THE_RESISTANCE_BOOTS;
    public static SBCustomItem PERFECT_BOOTS_9;
    public static SBCustomItem PERFECT_BOOTS_2;
    public static SBCustomItem BAT_PERSON_BOOTS;
    public static SBCustomItem SALMON_BOOTS;
    public static SBCustomItem STARRED_ADAPTIVE_BOOTS;
    public static SBCustomItem ARMOR_OF_MAGMA_BOOTS;
    public static SBCustomItem PROTECTOR_DRAGON_BOOTS;
    public static SBCustomItem ZOMBIE_KNIGHT_BOOTS;
    public static SBCustomItem PERFECT_BOOTS_6;
    public static SBCustomItem END_BOOTS;
    public static SBCustomItem PERFECT_BOOTS_4;
    public static SBCustomItem WEREWOLF_BOOTS;
    public static SBCustomItem FARM_ARMOR_BOOTS;
    public static SBCustomItem HARDENED_DIAMOND_BOOTS;
    public static SBCustomItem TANK_MINER_BOOTS;
    public static SBCustomItem PUMPKIN_BOOTS;
    public static SBCustomItem PERFECT_BOOTS_8;
    public static SBCustomItem CHEAP_TUXEDO_BOOTS;
    public static SBCustomItem FLAMEBREAKER_BOOTS;
    public static SBCustomItem FLAME_BREAKER_BOOTS;
    public static SBCustomItem FARMER_BOOTS;
    public static SBCustomItem TITAN_BOOTS;
    public static SBCustomItem SPEEDSTER_BOOTS;
    public static SBCustomItem MINOS_HUNTER_BOOTS;
    public static SBCustomItem WITHER_BOOTS;
    public static SBCustomItem ELEGANT_TUXEDO_BOOTS;
    public static SBCustomItem SHARK_SCALE_BOOTS;
    public static SBCustomItem FARM_SUIT_BOOTS;
    public static SBCustomItem MERCENARY_BOOTS;
    public static SBCustomItem CACTUS_BOOTS;
    public static SBCustomItem SPEED_WITHER_BOOTS;
    public static SBCustomItem YOUNG_DRAGON_BOOTS;
    public static SBCustomItem ZOMBIE_COMMANDER_BOOTS;
    public static SBCustomItem SKELETOR_BOOTS;
    public static SBCustomItem WISE_WITHER_BOOTS;
    public static SBCustomItem SKELETON_SOLDIER_BOOTS;
    public static SBCustomItem SPOOKY_BOOTS;
    public static SBCustomItem GREAT_SPOOK_BOOTS;
    public static SBCustomItem HYDRA1_BOOTS;
    public static SBCustomItem SPONGE_BOOTS;
    public static SBCustomItem SORROW_BOOTS;
    public static SBCustomItem STARRED_SHADOW_ASSASSIN_BOOTS;
    public static SBCustomItem BOOTS_OF_THE_PACK;
    public static SBCustomItem ZOMBIE_SOLDIER_BOOTS;
    public static SBCustomItem LAPIS_ARMOR_BOOTS;
    public static SBCustomItem HOLY_DRAGON_BOOTS;
    public static SBCustomItem PERFECT_BOOTS_3;
    public static SBCustomItem ROTTEN_BOOTS;
    public static SBCustomItem BLAZE_BOOTS;
    public static SBCustomItem GROWTH_BOOTS;
    public static SBCustomItem SEA_WALKER_BOOTS;
    public static SBCustomItem SALMON_BOOTS_NEW;
    public static SBCustomItem PERFECT_BOOTS_11;
    public static SBCustomItem MINERAL_BOOTS;
    public static SBCustomItem SPRING_BOOTS;
    public static SBCustomItem EMBER_BOOTS;
    public static SBCustomItem HEAT_BOOTS;
    public static SBCustomItem MINER_OUTFIT_BOOTS;
    public static SBCustomItem FAIRY_BOOTS;
    public static SBCustomItem PERFECT_BOOTS_10;
    public static SBCustomItem GHAST_BOOTS;
    public static SBCustomItem ANGLER_BOOTS;
    public static SBCustomItem PERFECT_BOOTS_5;
    public static SBCustomItem REVENANT_BOOTS;
    public static SBCustomItem CRYSTAL_BOOTS;
    public static SBCustomItem CRYPT_WITHERLORD_BOOTS;
    public static SBCustomItem EMPEROR_SHOES;
    public static SBCustomItem MASTIFF_BOOTS;
    public static SBCustomItem PERFECT_BOOTS_7;
    public static SBCustomItem SPIDER_BOOTS;
    public static SBCustomItem BOUNCY_BOOTS;
    public static SBCustomItem SNOW_SUIT_BOOTS;
    public static SBCustomItem RANCHERS_BOOTS;
    public static SBCustomItem PERFECT_BOOTS_1;
    public static SBCustomItem MUSHROOM_BOOTS;
    public static SBCustomItem STAR_BOOTS;
    public static SBCustomItem GOLEM_ARMOR_BOOTS;
    public static SBCustomItem SUPERIOR_DRAGON_BOOTS;
    public static SBCustomItem SKELETON_LORD_BOOTS;
    public static SBCustomItem FINAL_DESTINATION_BOOTS;
    public static SBCustomItem PERFECT_BOOTS_12;
    public static SBCustomItem BIG_SPRING_BOOTS;
    public static SBCustomItem GOBLIN_BOOTS;
    public static SBCustomItem GENERALS_ARMOR_OF_THE_RESISTANCE_BOOTS;
    public static SBCustomItem ARMOR_OF_YOG_BOOTS;
    public static SBCustomItem STARLIGHT_BOOTS;
    public static SBCustomItem LEAFLET_BOOTS;
    public static SBCustomItem TARANTULA_BOOTS;
    public static SBCustomItem ROSETTA_BOOTS;
    public static SBCustomItem SQUID_BOOTS;
    public static SBCustomItem STRONG_DRAGON_BOOTS;
    public static SBCustomItem FROZEN_BLAZE_BOOTS;
    public static SBCustomItem GLACITE_BOOTS;
    public static SBCustomItem TANK_WITHER_BOOTS;
    public static SBCustomItem FANCY_TUXEDO_BOOTS;
    public static SBCustomItem BIGGER_SPRING_BOOTS;
    public static SBCustomItem HEAVY_BOOTS;
    public static SBCustomItem ADAPTIVE_BOOTS;
    public static SBCustomItem EMERALD_ARMOR_BOOTS;
    public static SBCustomItem ZOMBIE_LORD_BOOTS;
    public static SBCustomItem NECROMANCER_LORD_BOOTS;
    public static SBCustomItem GHOST_BOOTS;



    public ItemsBOOTS(SkyBlock skyBlock) {
        SHADOW_ASSASSIN_BOOTS = new SBCustomItem("SHADOW_ASSASSIN_BOOTS", "Shadow Assassin Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(0,0,0), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SHADOW_ASSASSIN_BOOTS);
        OLD_DRAGON_BOOTS = new SBCustomItem("OLD_DRAGON_BOOTS", "Old Dragon Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(240,230,170), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(OLD_DRAGON_BOOTS);
        UNSTABLE_DRAGON_BOOTS = new SBCustomItem("UNSTABLE_DRAGON_BOOTS", "Unstable Dragon Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(178,18,227), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(UNSTABLE_DRAGON_BOOTS);
        SKELETON_MASTER_BOOTS = new SBCustomItem("SKELETON_MASTER_BOOTS", "Skeleton Master Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(255,107,11), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SKELETON_MASTER_BOOTS);
        SQUIRE_BOOTS = new SBCustomItem("SQUIRE_BOOTS", "Squire Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, Color.fromRGB(84,84,84), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SQUIRE_BOOTS);
        DIVER_BOOTS = new SBCustomItem("DIVER_BOOTS", "Diver's Boots", "", Material.GOLD_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(DIVER_BOOTS);
        WISE_DRAGON_BOOTS = new SBCustomItem("WISE_DRAGON_BOOTS", "Wise Dragon Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(41,240,233), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(WISE_DRAGON_BOOTS);
        THORNS_BOOTS = new SBCustomItem("THORNS_BOOTS", "Spirit Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(191,191,191), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(THORNS_BOOTS);
        POWER_WITHER_BOOTS = new SBCustomItem("POWER_WITHER_BOOTS", "Necron's Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(231,110,60), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(POWER_WITHER_BOOTS);
        DIVAN_BOOTS = new SBCustomItem("DIVAN_BOOTS", "Boots Of Divan", "", Material.GOLD_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(DIVAN_BOOTS);
        CELESTE_BOOTS = new SBCustomItem("CELESTE_BOOTS", "Celeste Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, Color.fromRGB(255,142,182), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(CELESTE_BOOTS);
        ZOMBIE_BOOTS = new SBCustomItem("ZOMBIE_BOOTS", "Zombie Boots", "", Material.DIAMOND_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(ZOMBIE_BOOTS);
        SKELETON_GRUNT_BOOTS = new SBCustomItem("SKELETON_GRUNT_BOOTS", "Skeleton Grunt Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(225,235,52), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SKELETON_GRUNT_BOOTS);
        DASHING_BOOTS = new SBCustomItem("DASHING_BOOTS", "Dashing Boots", "", Material.CHAINMAIL_BOOTS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(DASHING_BOOTS);
        SUPER_HEAVY_BOOTS = new SBCustomItem("SUPER_HEAVY_BOOTS", "Super Heavy Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(230,230,230), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SUPER_HEAVY_BOOTS);
        REAPER_BOOTS = new SBCustomItem("REAPER_BOOTS", "Reaper Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(27,27,27), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(REAPER_BOOTS);
        ARMOR_OF_THE_RESISTANCE_BOOTS = new SBCustomItem("ARMOR_OF_THE_RESISTANCE_BOOTS", "Boots of the Rising Sun", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(159,134,9), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(ARMOR_OF_THE_RESISTANCE_BOOTS);
        PERFECT_BOOTS_9 = new SBCustomItem("PERFECT_BOOTS_9", "Perfect Boots - Tier IX", "", Material.DIAMOND_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(PERFECT_BOOTS_9);
        PERFECT_BOOTS_2 = new SBCustomItem("PERFECT_BOOTS_2", "Perfect Boots - Tier II", "", Material.DIAMOND_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(PERFECT_BOOTS_2);
        BAT_PERSON_BOOTS = new SBCustomItem("BAT_PERSON_BOOTS", "Bat Person Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(0,0,0), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(BAT_PERSON_BOOTS);
        SALMON_BOOTS = new SBCustomItem("SALMON_BOOTS", "Salmon Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(193,60,15), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SALMON_BOOTS);
        STARRED_ADAPTIVE_BOOTS = new SBCustomItem("STARRED_ADAPTIVE_BOOTS", "Adaptive Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(191,188,178), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(STARRED_ADAPTIVE_BOOTS);
        ARMOR_OF_MAGMA_BOOTS = new SBCustomItem("ARMOR_OF_MAGMA_BOOTS", "Armor of Magma Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(255,147,0), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(ARMOR_OF_MAGMA_BOOTS);
        PROTECTOR_DRAGON_BOOTS = new SBCustomItem("PROTECTOR_DRAGON_BOOTS", "Protector Dragon Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(153,151,139), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(PROTECTOR_DRAGON_BOOTS);
        ZOMBIE_KNIGHT_BOOTS = new SBCustomItem("ZOMBIE_KNIGHT_BOOTS", "Zombie Knight Boots", "", Material.GOLD_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(ZOMBIE_KNIGHT_BOOTS);
        PERFECT_BOOTS_6 = new SBCustomItem("PERFECT_BOOTS_6", "Perfect Boots - Tier VI", "", Material.DIAMOND_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(PERFECT_BOOTS_6);
        END_BOOTS = new SBCustomItem("END_BOOTS", "Ender Boots", "", Material.CHAINMAIL_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(END_BOOTS);
        PERFECT_BOOTS_4 = new SBCustomItem("PERFECT_BOOTS_4", "Perfect Boots - Tier IV", "", Material.DIAMOND_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(PERFECT_BOOTS_4);
        WEREWOLF_BOOTS = new SBCustomItem("WEREWOLF_BOOTS", "Werewolf Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(29,17,5), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(WEREWOLF_BOOTS);
        FARM_ARMOR_BOOTS = new SBCustomItem("FARM_ARMOR_BOOTS", "Farm Armor Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(255,215,0), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(FARM_ARMOR_BOOTS);
        HARDENED_DIAMOND_BOOTS = new SBCustomItem("HARDENED_DIAMOND_BOOTS", "Hardened Diamond Boots", "", Material.DIAMOND_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(HARDENED_DIAMOND_BOOTS);
        TANK_MINER_BOOTS = new SBCustomItem("TANK_MINER_BOOTS", "Miner Boots", "", Material.DIAMOND_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(TANK_MINER_BOOTS);
        PUMPKIN_BOOTS = new SBCustomItem("PUMPKIN_BOOTS", "Pumpkin Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.COMMON, false, Color.fromRGB(237,170,54), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(PUMPKIN_BOOTS);
        PERFECT_BOOTS_8 = new SBCustomItem("PERFECT_BOOTS_8", "Perfect Boots - Tier VIII", "", Material.DIAMOND_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(PERFECT_BOOTS_8);
        CHEAP_TUXEDO_BOOTS = new SBCustomItem("CHEAP_TUXEDO_BOOTS", "Cheap Tuxedo Oxfords", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(56,56,56), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(CHEAP_TUXEDO_BOOTS);
        FLAMEBREAKER_BOOTS = new SBCustomItem("FLAMEBREAKER_BOOTS", "Ember Ash Boots", "", Material.CHAINMAIL_BOOTS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(FLAMEBREAKER_BOOTS);
        FLAME_BREAKER_BOOTS = new SBCustomItem("FLAME_BREAKER_BOOTS", "Flamebreaker Boots", "", Material.CHAINMAIL_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(FLAME_BREAKER_BOOTS);
        FARMER_BOOTS = new SBCustomItem("FARMER_BOOTS", "Farmer Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, Color.fromRGB(204,85,0), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(FARMER_BOOTS);
        TITAN_BOOTS = new SBCustomItem("TITAN_BOOTS", "Titan's Boots", "", Material.DIAMOND_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(TITAN_BOOTS);
        SPEEDSTER_BOOTS = new SBCustomItem("SPEEDSTER_BOOTS", "Speedster Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(224,252,247), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SPEEDSTER_BOOTS);
        MINOS_HUNTER_BOOTS = new SBCustomItem("MINOS_HUNTER_BOOTS", "Minos Hunter Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, Color.fromRGB(48,75,78), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(MINOS_HUNTER_BOOTS);
        WITHER_BOOTS = new SBCustomItem("WITHER_BOOTS", "Wither Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(0,0,0), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(WITHER_BOOTS);
        ELEGANT_TUXEDO_BOOTS = new SBCustomItem("ELEGANT_TUXEDO_BOOTS", "Elegant Tuxedo Oxfords", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(25,25,25), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(ELEGANT_TUXEDO_BOOTS);
        SHARK_SCALE_BOOTS = new SBCustomItem("SHARK_SCALE_BOOTS", "Shark Scale Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(0,44,166), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SHARK_SCALE_BOOTS);
        FARM_SUIT_BOOTS = new SBCustomItem("FARM_SUIT_BOOTS", "Farm Suit Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.COMMON, false, Color.fromRGB(255,255,0), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(FARM_SUIT_BOOTS);
        MERCENARY_BOOTS = new SBCustomItem("MERCENARY_BOOTS", "Mercenary Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(224,252,247), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(MERCENARY_BOOTS);
        CACTUS_BOOTS = new SBCustomItem("CACTUS_BOOTS", "Cactus Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.COMMON, false, Color.fromRGB(0,255,0), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(CACTUS_BOOTS);
        SPEED_WITHER_BOOTS = new SBCustomItem("SPEED_WITHER_BOOTS", "Maxor's Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(137,105,200), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SPEED_WITHER_BOOTS);
        YOUNG_DRAGON_BOOTS = new SBCustomItem("YOUNG_DRAGON_BOOTS", "Young Dragon Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(221,228,240), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(YOUNG_DRAGON_BOOTS);
        ZOMBIE_COMMANDER_BOOTS = new SBCustomItem("ZOMBIE_COMMANDER_BOOTS", "Zombie Commander Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(213,18,48), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(ZOMBIE_COMMANDER_BOOTS);
        SKELETOR_BOOTS = new SBCustomItem("SKELETOR_BOOTS", "Skeletor Boots", "", Material.CHAINMAIL_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(145,143,137), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SKELETOR_BOOTS);
        WISE_WITHER_BOOTS = new SBCustomItem("WISE_WITHER_BOOTS", "Storm's Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(28,212,228), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(WISE_WITHER_BOOTS);
        SKELETON_SOLDIER_BOOTS = new SBCustomItem("SKELETON_SOLDIER_BOOTS", "Skeleton Soldier Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(255,188,11), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SKELETON_SOLDIER_BOOTS);
        SPOOKY_BOOTS = new SBCustomItem("SPOOKY_BOOTS", "Spooky Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(96,96,96), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SPOOKY_BOOTS);
        GREAT_SPOOK_BOOTS = new SBCustomItem("GREAT_SPOOK_BOOTS", "Great Spook Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(153,51,153), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(GREAT_SPOOK_BOOTS);
        HYDRA1_BOOTS = new SBCustomItem("HYDRA1_BOOTS", "Water Hydra Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, Color.fromRGB(16,21,85), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(HYDRA1_BOOTS);
        SPONGE_BOOTS = new SBCustomItem("SPONGE_BOOTS", "Spongy Shoes", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(255,220,81), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SPONGE_BOOTS);
        SORROW_BOOTS = new SBCustomItem("SORROW_BOOTS", "Sorrow Boots", "", Material.CHAINMAIL_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SORROW_BOOTS);
        STARRED_SHADOW_ASSASSIN_BOOTS = new SBCustomItem("STARRED_SHADOW_ASSASSIN_BOOTS", "Shadow Assassin Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(0,0,0), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(STARRED_SHADOW_ASSASSIN_BOOTS);
        BOOTS_OF_THE_PACK = new SBCustomItem("BOOTS_OF_THE_PACK", "Boots of the Pack", "", Material.IRON_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(BOOTS_OF_THE_PACK);
        ZOMBIE_SOLDIER_BOOTS = new SBCustomItem("ZOMBIE_SOLDIER_BOOTS", "Zombie Soldier Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(208,127,0), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(ZOMBIE_SOLDIER_BOOTS);
        LAPIS_ARMOR_BOOTS = new SBCustomItem("LAPIS_ARMOR_BOOTS", "Lapis Armor Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, Color.fromRGB(0,0,255), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(LAPIS_ARMOR_BOOTS);
        HOLY_DRAGON_BOOTS = new SBCustomItem("HOLY_DRAGON_BOOTS", "Holy Dragon Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(71,209,71), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(HOLY_DRAGON_BOOTS);
        PERFECT_BOOTS_3 = new SBCustomItem("PERFECT_BOOTS_3", "Perfect Boots - Tier III", "", Material.DIAMOND_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(PERFECT_BOOTS_3);
        ROTTEN_BOOTS = new SBCustomItem("ROTTEN_BOOTS", "Rotten Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(158,112,3), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(ROTTEN_BOOTS);
        BLAZE_BOOTS = new SBCustomItem("BLAZE_BOOTS", "Blaze Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(247,218,51), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(BLAZE_BOOTS);
        GROWTH_BOOTS = new SBCustomItem("GROWTH_BOOTS", "Boots of Growth", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(0,190,0), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(GROWTH_BOOTS);
        SEA_WALKER_BOOTS = new SBCustomItem("SEA_WALKER_BOOTS", "Sea Walker Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, Color.fromRGB(16,97,110), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SEA_WALKER_BOOTS);
        SALMON_BOOTS_NEW = new SBCustomItem("SALMON_BOOTS_NEW", "Salmon Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(193,60,15), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SALMON_BOOTS_NEW);
        PERFECT_BOOTS_11 = new SBCustomItem("PERFECT_BOOTS_11", "Perfect Boots - Tier XI", "", Material.DIAMOND_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(PERFECT_BOOTS_11);
        MINERAL_BOOTS = new SBCustomItem("MINERAL_BOOTS", "Mineral Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(204,229,255), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(MINERAL_BOOTS);
        SPRING_BOOTS = new SBCustomItem("SPRING_BOOTS", "Spring Boots", "", Material.CHAINMAIL_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SPRING_BOOTS);
        EMBER_BOOTS = new SBCustomItem("EMBER_BOOTS", "Ember Boots", "", Material.CHAINMAIL_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(EMBER_BOOTS);
        HEAT_BOOTS = new SBCustomItem("HEAT_BOOTS", "Heat Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(179,179,179), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(HEAT_BOOTS);
        MINER_OUTFIT_BOOTS = new SBCustomItem("MINER_OUTFIT_BOOTS", "Miner's Outfit Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, Color.fromRGB(122,121,100), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(MINER_OUTFIT_BOOTS);
        FAIRY_BOOTS = new SBCustomItem("FAIRY_BOOTS", "Fairy's Galoshes", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(255,204,229), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(FAIRY_BOOTS);
        PERFECT_BOOTS_10 = new SBCustomItem("PERFECT_BOOTS_10", "Perfect Boots - Tier X", "", Material.DIAMOND_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(PERFECT_BOOTS_10);
        GHAST_BOOTS = new SBCustomItem("GHAST_BOOTS", "Ghast Boots", "", Material.CHAINMAIL_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(GHAST_BOOTS);
        ANGLER_BOOTS = new SBCustomItem("ANGLER_BOOTS", "Angler Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.COMMON, false, Color.fromRGB(11,0,79), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(ANGLER_BOOTS);
        PERFECT_BOOTS_5 = new SBCustomItem("PERFECT_BOOTS_5", "Perfect Boots - Tier V", "", Material.DIAMOND_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(PERFECT_BOOTS_5);
        REVENANT_BOOTS = new SBCustomItem("REVENANT_BOOTS", "Revenant Boots", "", Material.DIAMOND_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(REVENANT_BOOTS);
        CRYSTAL_BOOTS = new SBCustomItem("CRYSTAL_BOOTS", "Crystal Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(252,243,255), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(CRYSTAL_BOOTS);
        CRYPT_WITHERLORD_BOOTS = new SBCustomItem("CRYPT_WITHERLORD_BOOTS", "Crypt Witherlord Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(69,1,1), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(CRYPT_WITHERLORD_BOOTS);
        EMPEROR_SHOES = new SBCustomItem("EMPEROR_SHOES", "Emperor Shoes", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.COMMON, false, Color.fromRGB(153,13,0), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(EMPEROR_SHOES);
        MASTIFF_BOOTS = new SBCustomItem("MASTIFF_BOOTS", "Mastiff Boots", "", Material.DIAMOND_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(MASTIFF_BOOTS);
        PERFECT_BOOTS_7 = new SBCustomItem("PERFECT_BOOTS_7", "Perfect Boots - Tier VII", "", Material.DIAMOND_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(PERFECT_BOOTS_7);
        SPIDER_BOOTS = new SBCustomItem("SPIDER_BOOTS", "Spider's Boots", "", Material.IRON_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SPIDER_BOOTS);
        BOUNCY_BOOTS = new SBCustomItem("BOUNCY_BOOTS", "Bouncy Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(173,255,47), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(BOUNCY_BOOTS);
        SNOW_SUIT_BOOTS = new SBCustomItem("SNOW_SUIT_BOOTS", "Snow Suit Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(255,255,255), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SNOW_SUIT_BOOTS);
        RANCHERS_BOOTS = new SBCustomItem("RANCHERS_BOOTS", "Rancher's Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(0,0,0), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(RANCHERS_BOOTS);
        PERFECT_BOOTS_1 = new SBCustomItem("PERFECT_BOOTS_1", "Perfect Boots - Tier I", "", Material.DIAMOND_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(PERFECT_BOOTS_1);
        MUSHROOM_BOOTS = new SBCustomItem("MUSHROOM_BOOTS", "Mushroom Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.COMMON, false, Color.fromRGB(255,0,0), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(MUSHROOM_BOOTS);
        STAR_BOOTS = new SBCustomItem("STAR_BOOTS", "Boots of the Stars", "", Material.GOLD_BOOTS, (short) 0, "", SBCustomItem.Rarity.SPECIAL, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(STAR_BOOTS);
        GOLEM_ARMOR_BOOTS = new SBCustomItem("GOLEM_ARMOR_BOOTS", "Golem Armor Boots", "", Material.IRON_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(GOLEM_ARMOR_BOOTS);
        SUPERIOR_DRAGON_BOOTS = new SBCustomItem("SUPERIOR_DRAGON_BOOTS", "Superior Dragon Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(242,93,24), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SUPERIOR_DRAGON_BOOTS);
        SKELETON_LORD_BOOTS = new SBCustomItem("SKELETON_LORD_BOOTS", "Skeleton Lord Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(38,129,5), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SKELETON_LORD_BOOTS);
        FINAL_DESTINATION_BOOTS = new SBCustomItem("FINAL_DESTINATION_BOOTS", "Final Destination Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(10,0,17), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(FINAL_DESTINATION_BOOTS);
        PERFECT_BOOTS_12 = new SBCustomItem("PERFECT_BOOTS_12", "Perfect Boots - Tier XII", "", Material.DIAMOND_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(PERFECT_BOOTS_12);
        BIG_SPRING_BOOTS = new SBCustomItem("BIG_SPRING_BOOTS", "Big Spring Boots", "", Material.IRON_BOOTS, (short) 0, "", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(BIG_SPRING_BOOTS);
        GOBLIN_BOOTS = new SBCustomItem("GOBLIN_BOOTS", "Goblin Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(55,176,66), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(GOBLIN_BOOTS);
        GENERALS_ARMOR_OF_THE_RESISTANCE_BOOTS = new SBCustomItem("GENERALS_ARMOR_OF_THE_RESISTANCE_BOOTS", "Boots of the Rising Sun", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(159,134,9), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(GENERALS_ARMOR_OF_THE_RESISTANCE_BOOTS);
        ARMOR_OF_YOG_BOOTS = new SBCustomItem("ARMOR_OF_YOG_BOOTS", "Yog Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(200,50,0), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(ARMOR_OF_YOG_BOOTS);
        STARLIGHT_BOOTS = new SBCustomItem("STARLIGHT_BOOTS", "Starlight Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(212,0,255), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(STARLIGHT_BOOTS);
        LEAFLET_BOOTS = new SBCustomItem("LEAFLET_BOOTS", "Leaflet Sandals", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.COMMON, false, Color.fromRGB(77,204,77), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(LEAFLET_BOOTS);
        TARANTULA_BOOTS = new SBCustomItem("TARANTULA_BOOTS", "Tarantula Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(0,0,0), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(TARANTULA_BOOTS);
        ROSETTA_BOOTS = new SBCustomItem("ROSETTA_BOOTS", "Rosetta's Boots", "", Material.DIAMOND_BOOTS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(ROSETTA_BOOTS);
        SQUID_BOOTS = new SBCustomItem("SQUID_BOOTS", "Squid Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, Color.fromRGB(0,0,0), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(SQUID_BOOTS);
        STRONG_DRAGON_BOOTS = new SBCustomItem("STRONG_DRAGON_BOOTS", "Strong Dragon Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(240,209,36), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(STRONG_DRAGON_BOOTS);
        FROZEN_BLAZE_BOOTS = new SBCustomItem("FROZEN_BLAZE_BOOTS", "Frozen Blaze Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(160,218,239), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(FROZEN_BLAZE_BOOTS);
        GLACITE_BOOTS = new SBCustomItem("GLACITE_BOOTS", "Glacite Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(3,252,248), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(GLACITE_BOOTS);
        TANK_WITHER_BOOTS = new SBCustomItem("TANK_WITHER_BOOTS", "Goldor's Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(136,131,126), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(TANK_WITHER_BOOTS);
        FANCY_TUXEDO_BOOTS = new SBCustomItem("FANCY_TUXEDO_BOOTS", "Fancy Tuxedo Oxfords", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(51,42,42), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(FANCY_TUXEDO_BOOTS);
        BIGGER_SPRING_BOOTS = new SBCustomItem("BIGGER_SPRING_BOOTS", "Bigger Spring Boots", "", Material.IRON_BOOTS, (short) 0, "", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(BIGGER_SPRING_BOOTS);
        HEAVY_BOOTS = new SBCustomItem("HEAVY_BOOTS", "Heavy Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(255,255,255), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(HEAVY_BOOTS);
        ADAPTIVE_BOOTS = new SBCustomItem("ADAPTIVE_BOOTS", "Adaptive Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(191,188,178), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(ADAPTIVE_BOOTS);
        EMERALD_ARMOR_BOOTS = new SBCustomItem("EMERALD_ARMOR_BOOTS", "Emerald Armor Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(0,255,0), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(EMERALD_ARMOR_BOOTS);
        ZOMBIE_LORD_BOOTS = new SBCustomItem("ZOMBIE_LORD_BOOTS", "Zombie Lord Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(155,1,193), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(ZOMBIE_LORD_BOOTS);
        NECROMANCER_LORD_BOOTS = new SBCustomItem("NECROMANCER_LORD_BOOTS", "Necromancer Lord Boots", "", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(64,3,82), SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(NECROMANCER_LORD_BOOTS);
        GHOST_BOOTS = new SBCustomItem("GHOST_BOOTS", "Ghostly Boots", "§7§oBoots made of pure ghost essense", Material.LEATHER_BOOTS, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.BOOTS, skyBlock);
        SBItems.registerItem(GHOST_BOOTS);


    }

}

