
////////////////////////////////////////////////////////
//                                                    //
// File generated with Hypixel SkyBlock API           //
// Tool by fan87                                      //
// https://github.com/fan87/Hypixel-Skyblock-Remake   //
//                                                    //
// PLEASE CHECK "GENERATOIN" FILE FOR MORE INFO       //
//                                                    //
//                                                    //
////////////////////////////////////////////////////////


package me.fan87.commonplugin.item.init;

import me.fan87.commonplugin.SkyBlock;
import me.fan87.commonplugin.item.SBCustomItem;
import me.fan87.commonplugin.item.SBItems;
import me.fan87.commonplugin.item.impl.ItemVanilla;
import org.bukkit.Material;
import org.bukkit.Color;


// Start class: ItemsLEGGINGS
// Category: LEGGINGS
// Last Update: 2022-01-07 08:50:37.813824

public class ItemsLEGGINGS {

    public static SBCustomItem GOLD_LEGGINGS;
    public static SBCustomItem IRON_LEGGINGS;
    public static SBCustomItem CHAINMAIL_LEGGINGS;
    public static SBCustomItem DIAMOND_LEGGINGS;
    public static SBCustomItem LEATHER_LEGGINGS;
    public static SBCustomItem CHEAP_TUXEDO_LEGGINGS;
    public static SBCustomItem CELESTE_LEGGINGS;
    public static SBCustomItem MASTIFF_LEGGINGS;
    public static SBCustomItem GREAT_SPOOK_LEGGINGS;
    public static SBCustomItem TANK_MINER_LEGGINGS;
    public static SBCustomItem STARLIGHT_LEGGINGS;
    public static SBCustomItem SPEEDSTER_LEGGINGS;
    public static SBCustomItem SKELETON_SOLDIER_LEGGINGS;
    public static SBCustomItem ELEGANT_TUXEDO_LEGGINGS;
    public static SBCustomItem SKELETON_MASTER_LEGGINGS;
    public static SBCustomItem PERFECT_LEGGINGS_4;
    public static SBCustomItem YOUNG_DRAGON_LEGGINGS;
    public static SBCustomItem GENERALS_ARMOR_OF_THE_RESISTANCE_LEGGINGS;
    public static SBCustomItem ROSETTA_LEGGINGS;
    public static SBCustomItem BAT_PERSON_LEGGINGS;
    public static SBCustomItem END_LEGGINGS;
    public static SBCustomItem PERFECT_LEGGINGS_8;
    public static SBCustomItem SKELETOR_LEGGINGS;
    public static SBCustomItem ZOMBIE_SOLDIER_LEGGINGS;
    public static SBCustomItem MUSIC_PANTS;
    public static SBCustomItem ZOMBIE_LORD_LEGGINGS;
    public static SBCustomItem SALMON_LEGGINGS_NEW;
    public static SBCustomItem HOLY_DRAGON_LEGGINGS;
    public static SBCustomItem SKELETON_LORD_LEGGINGS;
    public static SBCustomItem PERFECT_LEGGINGS_5;
    public static SBCustomItem TANK_WITHER_LEGGINGS;
    public static SBCustomItem GOBLIN_LEGGINGS;
    public static SBCustomItem EMPEROR_LEGGINGS;
    public static SBCustomItem PERFECT_LEGGINGS_1;
    public static SBCustomItem HEAT_LEGGINGS;
    public static SBCustomItem BOUNCY_LEGGINGS;
    public static SBCustomItem FLAMEBREAKER_LEGGINGS;
    public static SBCustomItem WISE_DRAGON_LEGGINGS;
    public static SBCustomItem TITAN_LEGGINGS;
    public static SBCustomItem FLAME_BREAKER_LEGGINGS;
    public static SBCustomItem SUPERIOR_DRAGON_LEGGINGS;
    public static SBCustomItem FANCY_TUXEDO_LEGGINGS;
    public static SBCustomItem SHARK_SCALE_LEGGINGS;
    public static SBCustomItem PERFECT_LEGGINGS_2;
    public static SBCustomItem STARRED_SHADOW_ASSASSIN_LEGGINGS;
    public static SBCustomItem FARM_ARMOR_LEGGINGS;
    public static SBCustomItem CRYPT_WITHERLORD_LEGGINGS;
    public static SBCustomItem ROTTEN_LEGGINGS;
    public static SBCustomItem SHADOW_ASSASSIN_LEGGINGS;
    public static SBCustomItem WISE_WITHER_LEGGINGS;
    public static SBCustomItem GROWTH_LEGGINGS;
    public static SBCustomItem STRONG_DRAGON_LEGGINGS;
    public static SBCustomItem LEGGINGS_OF_THE_PACK;
    public static SBCustomItem SPONGE_LEGGINGS;
    public static SBCustomItem SNOW_SUIT_LEGGINGS;
    public static SBCustomItem SPEED_WITHER_LEGGINGS;
    public static SBCustomItem UNSTABLE_DRAGON_LEGGINGS;
    public static SBCustomItem SEA_WALKER_LEGGINGS;
    public static SBCustomItem ANGLER_LEGGINGS;
    public static SBCustomItem EMBER_LEGGINGS;
    public static SBCustomItem SORROW_LEGGINGS;
    public static SBCustomItem OLD_DRAGON_LEGGINGS;
    public static SBCustomItem FAIRY_LEGGINGS;
    public static SBCustomItem MINOS_HUNTER_LEGGINGS;
    public static SBCustomItem HARDENED_DIAMOND_LEGGINGS;
    public static SBCustomItem DIVAN_LEGGINGS;
    public static SBCustomItem FROZEN_BLAZE_LEGGINGS;
    public static SBCustomItem PROTECTOR_DRAGON_LEGGINGS;
    public static SBCustomItem DIVER_LEGGINGS;
    public static SBCustomItem ARMOR_OF_MAGMA_LEGGINGS;
    public static SBCustomItem ZOMBIE_LEGGINGS;
    public static SBCustomItem WEREWOLF_LEGGINGS;
    public static SBCustomItem NECROMANCER_LORD_LEGGINGS;
    public static SBCustomItem HYDRA1_LEGGINGS;
    public static SBCustomItem FINAL_DESTINATION_LEGGINGS;
    public static SBCustomItem FARM_SUIT_LEGGINGS;
    public static SBCustomItem CREEPER_LEGGINGS;
    public static SBCustomItem SQUIRE_LEGGINGS;
    public static SBCustomItem WITHER_LEGGINGS;
    public static SBCustomItem STARRED_ADAPTIVE_LEGGINGS;
    public static SBCustomItem MERCENARY_LEGGINGS;
    public static SBCustomItem CRYSTAL_LEGGINGS;
    public static SBCustomItem CACTUS_LEGGINGS;
    public static SBCustomItem HEAVY_LEGGINGS;
    public static SBCustomItem ARMOR_OF_YOG_LEGGINGS;
    public static SBCustomItem BLAZE_LEGGINGS;
    public static SBCustomItem GHAST_LEGGINGS;
    public static SBCustomItem ZOMBIE_COMMANDER_LEGGINGS;
    public static SBCustomItem PERFECT_LEGGINGS_7;
    public static SBCustomItem ADAPTIVE_LEGGINGS;
    public static SBCustomItem PERFECT_LEGGINGS_6;
    public static SBCustomItem PERFECT_LEGGINGS_3;
    public static SBCustomItem GLACITE_LEGGINGS;
    public static SBCustomItem LEAFLET_LEGGINGS;
    public static SBCustomItem POWER_WITHER_LEGGINGS;
    public static SBCustomItem EMERALD_ARMOR_LEGGINGS;
    public static SBCustomItem REAPER_LEGGINGS;
    public static SBCustomItem PERFECT_LEGGINGS_10;
    public static SBCustomItem LAPIS_ARMOR_LEGGINGS;
    public static SBCustomItem REVENANT_LEGGINGS;
    public static SBCustomItem SUPER_HEAVY_LEGGINGS;
    public static SBCustomItem STAR_LEGGINGS;
    public static SBCustomItem SKELETON_GRUNT_LEGGINGS;
    public static SBCustomItem ZOMBIE_KNIGHT_LEGGINGS;
    public static SBCustomItem GOLEM_ARMOR_LEGGINGS;
    public static SBCustomItem PERFECT_LEGGINGS_12;
    public static SBCustomItem SALMON_LEGGINGS;
    public static SBCustomItem TARANTULA_LEGGINGS;
    public static SBCustomItem PERFECT_LEGGINGS_11;
    public static SBCustomItem MINERAL_LEGGINGS;
    public static SBCustomItem MUSHROOM_LEGGINGS;
    public static SBCustomItem PERFECT_LEGGINGS_9;
    public static SBCustomItem SPOOKY_LEGGINGS;
    public static SBCustomItem MINER_OUTFIT_LEGGINGS;
    public static SBCustomItem ARMOR_OF_THE_RESISTANCE_LEGGINGS;
    public static SBCustomItem PUMPKIN_LEGGINGS;



    public ItemsLEGGINGS(SkyBlock skyBlock) {
        GOLD_LEGGINGS = new ItemVanilla("GOLD_LEGGINGS", "Golden Leggings", "", Material.GOLD_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(GOLD_LEGGINGS);
        IRON_LEGGINGS = new ItemVanilla("IRON_LEGGINGS", "Iron Leggings", "", Material.IRON_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(IRON_LEGGINGS);
        CHAINMAIL_LEGGINGS = new ItemVanilla("CHAINMAIL_LEGGINGS", "Chainmail Leggings", "", Material.CHAINMAIL_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(CHAINMAIL_LEGGINGS);
        DIAMOND_LEGGINGS = new ItemVanilla("DIAMOND_LEGGINGS", "Diamond Leggings", "", Material.DIAMOND_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(DIAMOND_LEGGINGS);
        LEATHER_LEGGINGS = new ItemVanilla("LEATHER_LEGGINGS", "Leather Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.COMMON, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(LEATHER_LEGGINGS);
        CHEAP_TUXEDO_LEGGINGS = new SBCustomItem("CHEAP_TUXEDO_LEGGINGS", "Cheap Tuxedo Pants", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(199,199,199), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(CHEAP_TUXEDO_LEGGINGS);
        CELESTE_LEGGINGS = new SBCustomItem("CELESTE_LEGGINGS", "Celeste Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, Color.fromRGB(255,142,202), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(CELESTE_LEGGINGS);
        MASTIFF_LEGGINGS = new SBCustomItem("MASTIFF_LEGGINGS", "Mastiff Leggings", "", Material.DIAMOND_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(MASTIFF_LEGGINGS);
        GREAT_SPOOK_LEGGINGS = new SBCustomItem("GREAT_SPOOK_LEGGINGS", "Great Spook Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(153,51,153), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(GREAT_SPOOK_LEGGINGS);
        TANK_MINER_LEGGINGS = new SBCustomItem("TANK_MINER_LEGGINGS", "Miner Leggings", "", Material.DIAMOND_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(122,121,100), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(TANK_MINER_LEGGINGS);
        STARLIGHT_LEGGINGS = new SBCustomItem("STARLIGHT_LEGGINGS", "Starlight Leggings", "", Material.GOLD_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(STARLIGHT_LEGGINGS);
        SPEEDSTER_LEGGINGS = new SBCustomItem("SPEEDSTER_LEGGINGS", "Speedster Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(224,252,247), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(SPEEDSTER_LEGGINGS);
        SKELETON_SOLDIER_LEGGINGS = new SBCustomItem("SKELETON_SOLDIER_LEGGINGS", "Skeleton Soldier Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(255,188,11), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(SKELETON_SOLDIER_LEGGINGS);
        ELEGANT_TUXEDO_LEGGINGS = new SBCustomItem("ELEGANT_TUXEDO_LEGGINGS", "Elegant Tuxedo Pants", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(254,253,252), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(ELEGANT_TUXEDO_LEGGINGS);
        SKELETON_MASTER_LEGGINGS = new SBCustomItem("SKELETON_MASTER_LEGGINGS", "Skeleton Master Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(255,107,11), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(SKELETON_MASTER_LEGGINGS);
        PERFECT_LEGGINGS_4 = new SBCustomItem("PERFECT_LEGGINGS_4", "Perfect Leggings - Tier IV", "", Material.DIAMOND_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(PERFECT_LEGGINGS_4);
        YOUNG_DRAGON_LEGGINGS = new SBCustomItem("YOUNG_DRAGON_LEGGINGS", "Young Dragon Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(221,228,240), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(YOUNG_DRAGON_LEGGINGS);
        GENERALS_ARMOR_OF_THE_RESISTANCE_LEGGINGS = new SBCustomItem("GENERALS_ARMOR_OF_THE_RESISTANCE_LEGGINGS", "Leggings of the Rising Sun", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(222,188,21), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(GENERALS_ARMOR_OF_THE_RESISTANCE_LEGGINGS);
        ROSETTA_LEGGINGS = new SBCustomItem("ROSETTA_LEGGINGS", "Rosetta's Leggings", "", Material.DIAMOND_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(ROSETTA_LEGGINGS);
        BAT_PERSON_LEGGINGS = new SBCustomItem("BAT_PERSON_LEGGINGS", "Bat Person Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(0,0,0), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(BAT_PERSON_LEGGINGS);
        END_LEGGINGS = new SBCustomItem("END_LEGGINGS", "Ender Leggings", "", Material.CHAINMAIL_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(END_LEGGINGS);
        PERFECT_LEGGINGS_8 = new SBCustomItem("PERFECT_LEGGINGS_8", "Perfect Leggings - Tier VIII", "", Material.DIAMOND_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(PERFECT_LEGGINGS_8);
        SKELETOR_LEGGINGS = new SBCustomItem("SKELETOR_LEGGINGS", "Skeletor Leggings", "", Material.CHAINMAIL_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(145,143,137), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(SKELETOR_LEGGINGS);
        ZOMBIE_SOLDIER_LEGGINGS = new SBCustomItem("ZOMBIE_SOLDIER_LEGGINGS", "Zombie Soldier Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(208,127,0), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(ZOMBIE_SOLDIER_LEGGINGS);
        MUSIC_PANTS = new SBCustomItem("MUSIC_PANTS", "Stereo Pants", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(4,207,211), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(MUSIC_PANTS);
        ZOMBIE_LORD_LEGGINGS = new SBCustomItem("ZOMBIE_LORD_LEGGINGS", "Zombie Lord Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(155,1,193), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(ZOMBIE_LORD_LEGGINGS);
        SALMON_LEGGINGS_NEW = new SBCustomItem("SALMON_LEGGINGS_NEW", "Salmon Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(168,43,118), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(SALMON_LEGGINGS_NEW);
        HOLY_DRAGON_LEGGINGS = new SBCustomItem("HOLY_DRAGON_LEGGINGS", "Holy Dragon Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(71,209,71), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(HOLY_DRAGON_LEGGINGS);
        SKELETON_LORD_LEGGINGS = new SBCustomItem("SKELETON_LORD_LEGGINGS", "Skeleton Lord Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(38,129,5), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(SKELETON_LORD_LEGGINGS);
        PERFECT_LEGGINGS_5 = new SBCustomItem("PERFECT_LEGGINGS_5", "Perfect Leggings - Tier V", "", Material.DIAMOND_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(PERFECT_LEGGINGS_5);
        TANK_WITHER_LEGGINGS = new SBCustomItem("TANK_WITHER_LEGGINGS", "Goldor's Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(101,96,90), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(TANK_WITHER_LEGGINGS);
        GOBLIN_LEGGINGS = new SBCustomItem("GOBLIN_LEGGINGS", "Goblin Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(55,176,66), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(GOBLIN_LEGGINGS);
        EMPEROR_LEGGINGS = new SBCustomItem("EMPEROR_LEGGINGS", "Emperor Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.COMMON, false, Color.fromRGB(153,13,0), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(EMPEROR_LEGGINGS);
        PERFECT_LEGGINGS_1 = new SBCustomItem("PERFECT_LEGGINGS_1", "Perfect Leggings - Tier I", "", Material.DIAMOND_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(PERFECT_LEGGINGS_1);
        HEAT_LEGGINGS = new SBCustomItem("HEAT_LEGGINGS", "Heat Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(179,179,179), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(HEAT_LEGGINGS);
        BOUNCY_LEGGINGS = new SBCustomItem("BOUNCY_LEGGINGS", "Bouncy Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(173,255,47), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(BOUNCY_LEGGINGS);
        FLAMEBREAKER_LEGGINGS = new SBCustomItem("FLAMEBREAKER_LEGGINGS", "Ember Ash Leggings", "", Material.CHAINMAIL_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(FLAMEBREAKER_LEGGINGS);
        WISE_DRAGON_LEGGINGS = new SBCustomItem("WISE_DRAGON_LEGGINGS", "Wise Dragon Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(41,240,233), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(WISE_DRAGON_LEGGINGS);
        TITAN_LEGGINGS = new SBCustomItem("TITAN_LEGGINGS", "Titan's Leggings", "", Material.DIAMOND_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(TITAN_LEGGINGS);
        FLAME_BREAKER_LEGGINGS = new SBCustomItem("FLAME_BREAKER_LEGGINGS", "Flamebreaker Leggings", "", Material.CHAINMAIL_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(FLAME_BREAKER_LEGGINGS);
        SUPERIOR_DRAGON_LEGGINGS = new SBCustomItem("SUPERIOR_DRAGON_LEGGINGS", "Superior Dragon Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(242,223,17), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(SUPERIOR_DRAGON_LEGGINGS);
        FANCY_TUXEDO_LEGGINGS = new SBCustomItem("FANCY_TUXEDO_LEGGINGS", "Fancy Tuxedo Pants", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(212,212,212), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(FANCY_TUXEDO_LEGGINGS);
        SHARK_SCALE_LEGGINGS = new SBCustomItem("SHARK_SCALE_LEGGINGS", "Shark Scale Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(0,44,166), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(SHARK_SCALE_LEGGINGS);
        PERFECT_LEGGINGS_2 = new SBCustomItem("PERFECT_LEGGINGS_2", "Perfect Leggings - Tier II", "", Material.DIAMOND_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(PERFECT_LEGGINGS_2);
        STARRED_SHADOW_ASSASSIN_LEGGINGS = new SBCustomItem("STARRED_SHADOW_ASSASSIN_LEGGINGS", "Shadow Assassin Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(0,0,0), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(STARRED_SHADOW_ASSASSIN_LEGGINGS);
        FARM_ARMOR_LEGGINGS = new SBCustomItem("FARM_ARMOR_LEGGINGS", "Farm Armor Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(255,215,0), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(FARM_ARMOR_LEGGINGS);
        CRYPT_WITHERLORD_LEGGINGS = new SBCustomItem("CRYPT_WITHERLORD_LEGGINGS", "Crypt Witherlord Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(69,1,1), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(CRYPT_WITHERLORD_LEGGINGS);
        ROTTEN_LEGGINGS = new SBCustomItem("ROTTEN_LEGGINGS", "Rotten Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(1,125,49), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(ROTTEN_LEGGINGS);
        SHADOW_ASSASSIN_LEGGINGS = new SBCustomItem("SHADOW_ASSASSIN_LEGGINGS", "Shadow Assassin Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(0,0,0), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(SHADOW_ASSASSIN_LEGGINGS);
        WISE_WITHER_LEGGINGS = new SBCustomItem("WISE_WITHER_LEGGINGS", "Storm's Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(23,168,196), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(WISE_WITHER_LEGGINGS);
        GROWTH_LEGGINGS = new SBCustomItem("GROWTH_LEGGINGS", "Leggings of Growth", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(0,190,0), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(GROWTH_LEGGINGS);
        STRONG_DRAGON_LEGGINGS = new SBCustomItem("STRONG_DRAGON_LEGGINGS", "Strong Dragon Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(224,148,25), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(STRONG_DRAGON_LEGGINGS);
        LEGGINGS_OF_THE_PACK = new SBCustomItem("LEGGINGS_OF_THE_PACK", "Leggings of the Pack", "", Material.IRON_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(LEGGINGS_OF_THE_PACK);
        SPONGE_LEGGINGS = new SBCustomItem("SPONGE_LEGGINGS", "Sponge Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(255,220,81), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(SPONGE_LEGGINGS);
        SNOW_SUIT_LEGGINGS = new SBCustomItem("SNOW_SUIT_LEGGINGS", "Snow Suit Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(255,255,255), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(SNOW_SUIT_LEGGINGS);
        SPEED_WITHER_LEGGINGS = new SBCustomItem("SPEED_WITHER_LEGGINGS", "Maxor's Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(93,47,185), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(SPEED_WITHER_LEGGINGS);
        UNSTABLE_DRAGON_LEGGINGS = new SBCustomItem("UNSTABLE_DRAGON_LEGGINGS", "Unstable Dragon Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(178,18,227), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(UNSTABLE_DRAGON_LEGGINGS);
        SEA_WALKER_LEGGINGS = new SBCustomItem("SEA_WALKER_LEGGINGS", "Sea Walker Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, Color.fromRGB(16,97,110), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(SEA_WALKER_LEGGINGS);
        ANGLER_LEGGINGS = new SBCustomItem("ANGLER_LEGGINGS", "Angler Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.COMMON, false, Color.fromRGB(11,0,79), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(ANGLER_LEGGINGS);
        EMBER_LEGGINGS = new SBCustomItem("EMBER_LEGGINGS", "Ember Leggings", "", Material.CHAINMAIL_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(EMBER_LEGGINGS);
        SORROW_LEGGINGS = new SBCustomItem("SORROW_LEGGINGS", "Sorrow Leggings", "", Material.CHAINMAIL_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(SORROW_LEGGINGS);
        OLD_DRAGON_LEGGINGS = new SBCustomItem("OLD_DRAGON_LEGGINGS", "Old Dragon Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(240,230,170), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(OLD_DRAGON_LEGGINGS);
        FAIRY_LEGGINGS = new SBCustomItem("FAIRY_LEGGINGS", "Fairy's Trousers", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(255,153,204), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(FAIRY_LEGGINGS);
        MINOS_HUNTER_LEGGINGS = new SBCustomItem("MINOS_HUNTER_LEGGINGS", "Minos Hunter Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, Color.fromRGB(255,10,10), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(MINOS_HUNTER_LEGGINGS);
        HARDENED_DIAMOND_LEGGINGS = new SBCustomItem("HARDENED_DIAMOND_LEGGINGS", "Hardened Diamond Leggings", "", Material.DIAMOND_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(HARDENED_DIAMOND_LEGGINGS);
        DIVAN_LEGGINGS = new SBCustomItem("DIVAN_LEGGINGS", "Leggings Of Divan", "", Material.GOLD_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(DIVAN_LEGGINGS);
        FROZEN_BLAZE_LEGGINGS = new SBCustomItem("FROZEN_BLAZE_LEGGINGS", "Frozen Blaze Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(160,218,239), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(FROZEN_BLAZE_LEGGINGS);
        PROTECTOR_DRAGON_LEGGINGS = new SBCustomItem("PROTECTOR_DRAGON_LEGGINGS", "Protector Dragon Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(153,151,139), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(PROTECTOR_DRAGON_LEGGINGS);
        DIVER_LEGGINGS = new SBCustomItem("DIVER_LEGGINGS", "Diver's Trunks", "", Material.GOLD_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(DIVER_LEGGINGS);
        ARMOR_OF_MAGMA_LEGGINGS = new SBCustomItem("ARMOR_OF_MAGMA_LEGGINGS", "Armor of Magma Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(255,147,0), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(ARMOR_OF_MAGMA_LEGGINGS);
        ZOMBIE_LEGGINGS = new SBCustomItem("ZOMBIE_LEGGINGS", "Zombie Leggings", "", Material.DIAMOND_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(ZOMBIE_LEGGINGS);
        WEREWOLF_LEGGINGS = new SBCustomItem("WEREWOLF_LEGGINGS", "Werewolf Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(29,17,5), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(WEREWOLF_LEGGINGS);
        NECROMANCER_LORD_LEGGINGS = new SBCustomItem("NECROMANCER_LORD_LEGGINGS", "Necromancer Lord Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(55,1,71), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(NECROMANCER_LORD_LEGGINGS);
        HYDRA1_LEGGINGS = new SBCustomItem("HYDRA1_LEGGINGS", "Water Hydra Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, Color.fromRGB(16,21,85), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(HYDRA1_LEGGINGS);
        FINAL_DESTINATION_LEGGINGS = new SBCustomItem("FINAL_DESTINATION_LEGGINGS", "Final Destination Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(255,117,255), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(FINAL_DESTINATION_LEGGINGS);
        FARM_SUIT_LEGGINGS = new SBCustomItem("FARM_SUIT_LEGGINGS", "Farm Suit Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.COMMON, false, Color.fromRGB(255,255,0), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(FARM_SUIT_LEGGINGS);
        CREEPER_LEGGINGS = new SBCustomItem("CREEPER_LEGGINGS", "Creeper Pants", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(122,232,44), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(CREEPER_LEGGINGS);
        SQUIRE_LEGGINGS = new SBCustomItem("SQUIRE_LEGGINGS", "Squire Leggings", "", Material.CHAINMAIL_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(SQUIRE_LEGGINGS);
        WITHER_LEGGINGS = new SBCustomItem("WITHER_LEGGINGS", "Wither Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(0,0,0), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(WITHER_LEGGINGS);
        STARRED_ADAPTIVE_LEGGINGS = new SBCustomItem("STARRED_ADAPTIVE_LEGGINGS", "Adaptive Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(191,188,178), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(STARRED_ADAPTIVE_LEGGINGS);
        MERCENARY_LEGGINGS = new SBCustomItem("MERCENARY_LEGGINGS", "Mercenary Leggings", "", Material.CHAINMAIL_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(MERCENARY_LEGGINGS);
        CRYSTAL_LEGGINGS = new SBCustomItem("CRYSTAL_LEGGINGS", "Crystal Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(252,243,255), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(CRYSTAL_LEGGINGS);
        CACTUS_LEGGINGS = new SBCustomItem("CACTUS_LEGGINGS", "Cactus Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.COMMON, false, Color.fromRGB(0,255,0), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(CACTUS_LEGGINGS);
        HEAVY_LEGGINGS = new SBCustomItem("HEAVY_LEGGINGS", "Heavy Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.RARE, false, Color.fromRGB(130,130,130), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(HEAVY_LEGGINGS);
        ARMOR_OF_YOG_LEGGINGS = new SBCustomItem("ARMOR_OF_YOG_LEGGINGS", "Yog Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(200,50,0), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(ARMOR_OF_YOG_LEGGINGS);
        BLAZE_LEGGINGS = new SBCustomItem("BLAZE_LEGGINGS", "Blaze Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(247,218,51), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(BLAZE_LEGGINGS);
        GHAST_LEGGINGS = new SBCustomItem("GHAST_LEGGINGS", "Ghast Leggings", "", Material.CHAINMAIL_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(GHAST_LEGGINGS);
        ZOMBIE_COMMANDER_LEGGINGS = new SBCustomItem("ZOMBIE_COMMANDER_LEGGINGS", "Zombie Commander Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(213,18,48), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(ZOMBIE_COMMANDER_LEGGINGS);
        PERFECT_LEGGINGS_7 = new SBCustomItem("PERFECT_LEGGINGS_7", "Perfect Leggings - Tier VII", "", Material.DIAMOND_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(PERFECT_LEGGINGS_7);
        ADAPTIVE_LEGGINGS = new SBCustomItem("ADAPTIVE_LEGGINGS", "Adaptive Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(191,188,178), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(ADAPTIVE_LEGGINGS);
        PERFECT_LEGGINGS_6 = new SBCustomItem("PERFECT_LEGGINGS_6", "Perfect Leggings - Tier VI", "", Material.DIAMOND_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(PERFECT_LEGGINGS_6);
        PERFECT_LEGGINGS_3 = new SBCustomItem("PERFECT_LEGGINGS_3", "Perfect Leggings - Tier III", "", Material.DIAMOND_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(PERFECT_LEGGINGS_3);
        GLACITE_LEGGINGS = new SBCustomItem("GLACITE_LEGGINGS", "Glacite Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(3,252,248), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(GLACITE_LEGGINGS);
        LEAFLET_LEGGINGS = new SBCustomItem("LEAFLET_LEGGINGS", "Leaflet Pants", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.COMMON, false, Color.fromRGB(77,204,77), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(LEAFLET_LEGGINGS);
        POWER_WITHER_LEGGINGS = new SBCustomItem("POWER_WITHER_LEGGINGS", "Necron's Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(231,92,60), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(POWER_WITHER_LEGGINGS);
        EMERALD_ARMOR_LEGGINGS = new SBCustomItem("EMERALD_ARMOR_LEGGINGS", "Emerald Armor Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(0,255,0), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(EMERALD_ARMOR_LEGGINGS);
        REAPER_LEGGINGS = new SBCustomItem("REAPER_LEGGINGS", "Reaper Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, Color.fromRGB(27,27,27), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(REAPER_LEGGINGS);
        PERFECT_LEGGINGS_10 = new SBCustomItem("PERFECT_LEGGINGS_10", "Perfect Leggings - Tier X", "", Material.DIAMOND_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(PERFECT_LEGGINGS_10);
        LAPIS_ARMOR_LEGGINGS = new SBCustomItem("LAPIS_ARMOR_LEGGINGS", "Lapis Armor Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, Color.fromRGB(0,0,255), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(LAPIS_ARMOR_LEGGINGS);
        REVENANT_LEGGINGS = new SBCustomItem("REVENANT_LEGGINGS", "Revenant Leggings", "", Material.DIAMOND_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(REVENANT_LEGGINGS);
        SUPER_HEAVY_LEGGINGS = new SBCustomItem("SUPER_HEAVY_LEGGINGS", "Super Heavy Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(90,100,100), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(SUPER_HEAVY_LEGGINGS);
        STAR_LEGGINGS = new SBCustomItem("STAR_LEGGINGS", "Leggings of the Stars", "", Material.GOLD_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.SPECIAL, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(STAR_LEGGINGS);
        SKELETON_GRUNT_LEGGINGS = new SBCustomItem("SKELETON_GRUNT_LEGGINGS", "Skeleton Grunt Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(225,235,52), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(SKELETON_GRUNT_LEGGINGS);
        ZOMBIE_KNIGHT_LEGGINGS = new SBCustomItem("ZOMBIE_KNIGHT_LEGGINGS", "Zombie Knight Leggings", "", Material.GOLD_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(ZOMBIE_KNIGHT_LEGGINGS);
        GOLEM_ARMOR_LEGGINGS = new SBCustomItem("GOLEM_ARMOR_LEGGINGS", "Golem Armor Leggings", "", Material.IRON_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.RARE, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(GOLEM_ARMOR_LEGGINGS);
        PERFECT_LEGGINGS_12 = new SBCustomItem("PERFECT_LEGGINGS_12", "Perfect Leggings - Tier XII", "", Material.DIAMOND_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(PERFECT_LEGGINGS_12);
        SALMON_LEGGINGS = new SBCustomItem("SALMON_LEGGINGS", "Salmon Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(168,43,118), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(SALMON_LEGGINGS);
        TARANTULA_LEGGINGS = new SBCustomItem("TARANTULA_LEGGINGS", "Tarantula Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(0,0,0), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(TARANTULA_LEGGINGS);
        PERFECT_LEGGINGS_11 = new SBCustomItem("PERFECT_LEGGINGS_11", "Perfect Leggings - Tier XI", "", Material.DIAMOND_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(PERFECT_LEGGINGS_11);
        MINERAL_LEGGINGS = new SBCustomItem("MINERAL_LEGGINGS", "Mineral Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(204,229,255), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(MINERAL_LEGGINGS);
        MUSHROOM_LEGGINGS = new SBCustomItem("MUSHROOM_LEGGINGS", "Mushroom Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.COMMON, false, Color.fromRGB(255,0,0), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(MUSHROOM_LEGGINGS);
        PERFECT_LEGGINGS_9 = new SBCustomItem("PERFECT_LEGGINGS_9", "Perfect Leggings - Tier IX", "", Material.DIAMOND_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, null, SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(PERFECT_LEGGINGS_9);
        SPOOKY_LEGGINGS = new SBCustomItem("SPOOKY_LEGGINGS", "Spooky Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(96,96,96), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(SPOOKY_LEGGINGS);
        MINER_OUTFIT_LEGGINGS = new SBCustomItem("MINER_OUTFIT_LEGGINGS", "Miner's Outfit Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, Color.fromRGB(122,121,100), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(MINER_OUTFIT_LEGGINGS);
        ARMOR_OF_THE_RESISTANCE_LEGGINGS = new SBCustomItem("ARMOR_OF_THE_RESISTANCE_LEGGINGS", "Leggings of the Rising Sun", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.EPIC, false, Color.fromRGB(222,188,21), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(ARMOR_OF_THE_RESISTANCE_LEGGINGS);
        PUMPKIN_LEGGINGS = new SBCustomItem("PUMPKIN_LEGGINGS", "Pumpkin Leggings", "", Material.LEATHER_LEGGINGS, (short) 0, "", SBCustomItem.Rarity.COMMON, false, Color.fromRGB(237,170,54), SBCustomItem.Category.LEGGINGS, skyBlock);
        SBItems.registerItem(PUMPKIN_LEGGINGS);


    }

}

