

// File generated with Hypixel SkyBlock API
// Tool by fan87

package me.fan87.commonplugin.item.init;

import me.fan87.commonplugin.SkyBlock;
import me.fan87.commonplugin.item.SBCustomItem;
import me.fan87.commonplugin.item.SBItems;
import me.fan87.commonplugin.item.impl.ItemVanilla;
import org.bukkit.Material;

public class ItemsCHESTPLATE {

    public static SBCustomItem GOLD_CHESTPLATE;
    public static SBCustomItem CHAINMAIL_CHESTPLATE;
    public static SBCustomItem LEATHER_CHESTPLATE;
    public static SBCustomItem IRON_CHESTPLATE;
    public static SBCustomItem DIAMOND_CHESTPLATE;
    public static SBCustomItem FARM_ARMOR_CHESTPLATE;
    public static SBCustomItem PERFECT_CHESTPLATE_3;
    public static SBCustomItem MINOS_HUNTER_CHESTPLATE;
    public static SBCustomItem WEREWOLF_CHESTPLATE;
    public static SBCustomItem WITHER_CHESTPLATE;
    public static SBCustomItem SEA_WALKER_CHESTPLATE;
    public static SBCustomItem SKELETON_LORD_CHESTPLATE;
    public static SBCustomItem FLAMEBREAKER_CHESTPLATE;
    public static SBCustomItem CRYSTAL_CHESTPLATE;
    public static SBCustomItem SKELETON_MASTER_CHESTPLATE;
    public static SBCustomItem MITHRIL_COAT;
    public static SBCustomItem GREAT_SPOOK_CHESTPLATE;
    public static SBCustomItem STONE_CHESTPLATE;
    public static SBCustomItem CHESTPLATE_OF_THE_PACK;
    public static SBCustomItem BOUNCY_CHESTPLATE;
    public static SBCustomItem TANK_WITHER_CHESTPLATE;
    public static SBCustomItem PERFECT_CHESTPLATE_7;
    public static SBCustomItem SKELETON_GRUNT_CHESTPLATE;
    public static SBCustomItem YOUNG_DRAGON_CHESTPLATE;
    public static SBCustomItem UNSTABLE_DRAGON_CHESTPLATE;
    public static SBCustomItem BAT_PERSON_CHESTPLATE;
    public static SBCustomItem ARMOR_OF_YOG_CHESTPLATE;
    public static SBCustomItem SKELETOR_CHESTPLATE;
    public static SBCustomItem CHEAP_TUXEDO_CHESTPLATE;
    public static SBCustomItem FAIRY_CHESTPLATE;
    public static SBCustomItem SUPERIOR_DRAGON_CHESTPLATE;
    public static SBCustomItem HARDENED_DIAMOND_CHESTPLATE;
    public static SBCustomItem HOLY_DRAGON_CHESTPLATE;
    public static SBCustomItem CACTUS_CHESTPLATE;
    public static SBCustomItem STEEL_CHESTPLATE;
    public static SBCustomItem POWER_WITHER_CHESTPLATE;
    public static SBCustomItem STAR_CHESTPLATE;
    public static SBCustomItem GOBLIN_CHESTPLATE;
    public static SBCustomItem ROSETTA_CHESTPLATE;
    public static SBCustomItem ELEGANT_TUXEDO_CHESTPLATE;
    public static SBCustomItem OLD_DRAGON_CHESTPLATE;
    public static SBCustomItem ZOMBIE_COMMANDER_CHESTPLATE;
    public static SBCustomItem PERFECT_CHESTPLATE_2;
    public static SBCustomItem STARLIGHT_CHESTPLATE;
    public static SBCustomItem GLACITE_CHESTPLATE;
    public static SBCustomItem TARANTULA_CHESTPLATE;
    public static SBCustomItem PUMPKIN_CHESTPLATE;
    public static SBCustomItem TANK_MINER_CHESTPLATE;
    public static SBCustomItem GHAST_CHESTPLATE;
    public static SBCustomItem REVENANT_CHESTPLATE;
    public static SBCustomItem PERFECT_CHESTPLATE_9;
    public static SBCustomItem CELESTE_CHESTPLATE;
    public static SBCustomItem LAPIS_ARMOR_CHESTPLATE;
    public static SBCustomItem SNOW_SUIT_CHESTPLATE;
    public static SBCustomItem SPEEDSTER_CHESTPLATE;
    public static SBCustomItem ZOMBIE_KNIGHT_CHESTPLATE;
    public static SBCustomItem SPOOKY_CHESTPLATE;
    public static SBCustomItem SPEED_WITHER_CHESTPLATE;
    public static SBCustomItem PROTECTOR_DRAGON_CHESTPLATE;
    public static SBCustomItem GROWTH_CHESTPLATE;
    public static SBCustomItem FINAL_DESTINATION_CHESTPLATE;
    public static SBCustomItem PERFECT_CHESTPLATE_5;
    public static SBCustomItem GUARDIAN_CHESTPLATE;
    public static SBCustomItem EMBER_CHESTPLATE;
    public static SBCustomItem MERCENARY_CHESTPLATE;
    public static SBCustomItem FARM_SUIT_CHESTPLATE;
    public static SBCustomItem FROZEN_BLAZE_CHESTPLATE;
    public static SBCustomItem EMERALD_ARMOR_CHESTPLATE;
    public static SBCustomItem METAL_CHESTPLATE;
    public static SBCustomItem REAPER_CHESTPLATE;
    public static SBCustomItem SKELETON_SOLDIER_CHESTPLATE;
    public static SBCustomItem WISE_DRAGON_CHESTPLATE;
    public static SBCustomItem NECROMANCER_LORD_CHESTPLATE;
    public static SBCustomItem SALMON_CHESTPLATE_NEW;
    public static SBCustomItem GENERALS_ARMOR_OF_THE_RESISTANCE_CHESTPLATE;
    public static SBCustomItem ZOMBIE_CHESTPLATE;
    public static SBCustomItem MINER_OUTFIT_CHESTPLATE;
    public static SBCustomItem EMPEROR_ROBES;
    public static SBCustomItem MUSHROOM_CHESTPLATE;
    public static SBCustomItem HEAVY_CHESTPLATE;
    public static SBCustomItem BLAZE_CHESTPLATE;
    public static SBCustomItem LEAFLET_CHESTPLATE;
    public static SBCustomItem SHARK_SCALE_CHESTPLATE;
    public static SBCustomItem SHADOW_ASSASSIN_CHESTPLATE;
    public static SBCustomItem HEAT_CHESTPLATE;
    public static SBCustomItem FALLEN_STAR_CHESTPLATE;
    public static SBCustomItem HYDRA1_CHESTPLATE;
    public static SBCustomItem ADAPTIVE_CHESTPLATE;
    public static SBCustomItem DIVAN_CHESTPLATE;
    public static SBCustomItem DIVER_CHESTPLATE;
    public static SBCustomItem ANGLER_CHESTPLATE;
    public static SBCustomItem SUPER_HEAVY_CHESTPLATE;
    public static SBCustomItem OBSIDIAN_CHESTPLATE;
    public static SBCustomItem PERFECT_CHESTPLATE_8;
    public static SBCustomItem SALMON_CHESTPLATE;
    public static SBCustomItem MASTIFF_CHESTPLATE;
    public static SBCustomItem ROTTEN_CHESTPLATE;
    public static SBCustomItem SORROW_CHESTPLATE;
    public static SBCustomItem FALLEN_STAR_BOOTS;
    public static SBCustomItem GOLEM_ARMOR_CHESTPLATE;
    public static SBCustomItem SPONGE_CHESTPLATE;
    public static SBCustomItem STARRED_ADAPTIVE_CHESTPLATE;
    public static SBCustomItem FLAME_BREAKER_CHESTPLATE;
    public static SBCustomItem SQUIRE_CHESTPLATE;
    public static SBCustomItem ARMOR_OF_MAGMA_CHESTPLATE;
    public static SBCustomItem END_CHESTPLATE;
    public static SBCustomItem PERFECT_CHESTPLATE_10;
    public static SBCustomItem TITAN_CHESTPLATE;
    public static SBCustomItem PERFECT_CHESTPLATE_11;
    public static SBCustomItem ZOMBIE_LORD_CHESTPLATE;
    public static SBCustomItem MINERAL_CHESTPLATE;
    public static SBCustomItem PERFECT_CHESTPLATE_12;
    public static SBCustomItem FANCY_TUXEDO_CHESTPLATE;
    public static SBCustomItem PERFECT_CHESTPLATE_6;
    public static SBCustomItem PERFECT_CHESTPLATE_1;
    public static SBCustomItem CRYPT_WITHERLORD_CHESTPLATE;
    public static SBCustomItem FALLEN_STAR_LEGGINGS;
    public static SBCustomItem WISE_WITHER_CHESTPLATE;
    public static SBCustomItem PERFECT_CHESTPLATE_4;
    public static SBCustomItem STRONG_DRAGON_CHESTPLATE;
    public static SBCustomItem ARMOR_OF_THE_RESISTANCE_CHESTPLATE;
    public static SBCustomItem STARRED_SHADOW_ASSASSIN_CHESTPLATE;
    public static SBCustomItem ZOMBIE_SOLDIER_CHESTPLATE;



    public ItemsCHESTPLATE(SkyBlock skyBlock) {
        GOLD_CHESTPLATE = new ItemVanilla("GOLD_CHESTPLATE", "Golden Chestplate", "", Material.GOLD_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.COMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(GOLD_CHESTPLATE);
        CHAINMAIL_CHESTPLATE = new ItemVanilla("CHAINMAIL_CHESTPLATE", "Chainmail Chestplate", "", Material.CHAINMAIL_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(CHAINMAIL_CHESTPLATE);
        LEATHER_CHESTPLATE = new ItemVanilla("LEATHER_CHESTPLATE", "Leather Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.COMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(LEATHER_CHESTPLATE);
        IRON_CHESTPLATE = new ItemVanilla("IRON_CHESTPLATE", "Iron Chestplate", "", Material.IRON_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.COMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(IRON_CHESTPLATE);
        DIAMOND_CHESTPLATE = new ItemVanilla("DIAMOND_CHESTPLATE", "Diamond Chestplate", "", Material.DIAMOND_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(DIAMOND_CHESTPLATE);
        FARM_ARMOR_CHESTPLATE = new SBCustomItem("FARM_ARMOR_CHESTPLATE", "Farm Armor Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.RARE, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(FARM_ARMOR_CHESTPLATE);
        PERFECT_CHESTPLATE_3 = new SBCustomItem("PERFECT_CHESTPLATE_3", "Perfect Chestplate - Tier III", "", Material.DIAMOND_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.RARE, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(PERFECT_CHESTPLATE_3);
        MINOS_HUNTER_CHESTPLATE = new SBCustomItem("MINOS_HUNTER_CHESTPLATE", "Minos Hunter Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(MINOS_HUNTER_CHESTPLATE);
        WEREWOLF_CHESTPLATE = new SBCustomItem("WEREWOLF_CHESTPLATE", "Werewolf Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(WEREWOLF_CHESTPLATE);
        WITHER_CHESTPLATE = new SBCustomItem("WITHER_CHESTPLATE", "Wither Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(WITHER_CHESTPLATE);
        SEA_WALKER_CHESTPLATE = new SBCustomItem("SEA_WALKER_CHESTPLATE", "Sea Walker Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(SEA_WALKER_CHESTPLATE);
        SKELETON_LORD_CHESTPLATE = new SBCustomItem("SKELETON_LORD_CHESTPLATE", "Skeleton Lord Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(SKELETON_LORD_CHESTPLATE);
        FLAMEBREAKER_CHESTPLATE = new SBCustomItem("FLAMEBREAKER_CHESTPLATE", "Ember Ash Chestplate", "", Material.CHAINMAIL_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(FLAMEBREAKER_CHESTPLATE);
        CRYSTAL_CHESTPLATE = new SBCustomItem("CRYSTAL_CHESTPLATE", "Crystal Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(CRYSTAL_CHESTPLATE);
        SKELETON_MASTER_CHESTPLATE = new SBCustomItem("SKELETON_MASTER_CHESTPLATE", "Skeleton Master Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(SKELETON_MASTER_CHESTPLATE);
        MITHRIL_COAT = new SBCustomItem("MITHRIL_COAT", "Mithril Coat", "", Material.CHAINMAIL_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(MITHRIL_COAT);
        GREAT_SPOOK_CHESTPLATE = new SBCustomItem("GREAT_SPOOK_CHESTPLATE", "Great Spook Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(GREAT_SPOOK_CHESTPLATE);
        STONE_CHESTPLATE = new SBCustomItem("STONE_CHESTPLATE", "Stone Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.RARE, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(STONE_CHESTPLATE);
        CHESTPLATE_OF_THE_PACK = new SBCustomItem("CHESTPLATE_OF_THE_PACK", "Chestplate of the Pack", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(CHESTPLATE_OF_THE_PACK);
        BOUNCY_CHESTPLATE = new SBCustomItem("BOUNCY_CHESTPLATE", "Bouncy Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.RARE, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(BOUNCY_CHESTPLATE);
        TANK_WITHER_CHESTPLATE = new SBCustomItem("TANK_WITHER_CHESTPLATE", "Goldor's Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(TANK_WITHER_CHESTPLATE);
        PERFECT_CHESTPLATE_7 = new SBCustomItem("PERFECT_CHESTPLATE_7", "Perfect Chestplate - Tier VII", "", Material.DIAMOND_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(PERFECT_CHESTPLATE_7);
        SKELETON_GRUNT_CHESTPLATE = new SBCustomItem("SKELETON_GRUNT_CHESTPLATE", "Skeleton Grunt Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(SKELETON_GRUNT_CHESTPLATE);
        YOUNG_DRAGON_CHESTPLATE = new SBCustomItem("YOUNG_DRAGON_CHESTPLATE", "Young Dragon Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(YOUNG_DRAGON_CHESTPLATE);
        UNSTABLE_DRAGON_CHESTPLATE = new SBCustomItem("UNSTABLE_DRAGON_CHESTPLATE", "Unstable Dragon Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(UNSTABLE_DRAGON_CHESTPLATE);
        BAT_PERSON_CHESTPLATE = new SBCustomItem("BAT_PERSON_CHESTPLATE", "Bat Person Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(BAT_PERSON_CHESTPLATE);
        ARMOR_OF_YOG_CHESTPLATE = new SBCustomItem("ARMOR_OF_YOG_CHESTPLATE", "Yog Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(ARMOR_OF_YOG_CHESTPLATE);
        SKELETOR_CHESTPLATE = new SBCustomItem("SKELETOR_CHESTPLATE", "Skeletor Chestplate", "", Material.CHAINMAIL_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(SKELETOR_CHESTPLATE);
        CHEAP_TUXEDO_CHESTPLATE = new SBCustomItem("CHEAP_TUXEDO_CHESTPLATE", "Cheap Tuxedo Jacket", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(CHEAP_TUXEDO_CHESTPLATE);
        FAIRY_CHESTPLATE = new SBCustomItem("FAIRY_CHESTPLATE", "Fairy's Polo", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.RARE, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(FAIRY_CHESTPLATE);
        SUPERIOR_DRAGON_CHESTPLATE = new SBCustomItem("SUPERIOR_DRAGON_CHESTPLATE", "Superior Dragon Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(SUPERIOR_DRAGON_CHESTPLATE);
        HARDENED_DIAMOND_CHESTPLATE = new SBCustomItem("HARDENED_DIAMOND_CHESTPLATE", "Hardened Diamond Chestplate", "", Material.DIAMOND_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.RARE, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(HARDENED_DIAMOND_CHESTPLATE);
        HOLY_DRAGON_CHESTPLATE = new SBCustomItem("HOLY_DRAGON_CHESTPLATE", "Holy Dragon Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(HOLY_DRAGON_CHESTPLATE);
        CACTUS_CHESTPLATE = new SBCustomItem("CACTUS_CHESTPLATE", "Cactus Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.COMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(CACTUS_CHESTPLATE);
        STEEL_CHESTPLATE = new SBCustomItem("STEEL_CHESTPLATE", "Steel Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(STEEL_CHESTPLATE);
        POWER_WITHER_CHESTPLATE = new SBCustomItem("POWER_WITHER_CHESTPLATE", "Necron's Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(POWER_WITHER_CHESTPLATE);
        STAR_CHESTPLATE = new SBCustomItem("STAR_CHESTPLATE", "Chestplate of the Stars", "", Material.GOLD_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.SPECIAL, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(STAR_CHESTPLATE);
        GOBLIN_CHESTPLATE = new SBCustomItem("GOBLIN_CHESTPLATE", "Goblin Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.RARE, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(GOBLIN_CHESTPLATE);
        ROSETTA_CHESTPLATE = new SBCustomItem("ROSETTA_CHESTPLATE", "Rosetta's Chestplate", "", Material.DIAMOND_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(ROSETTA_CHESTPLATE);
        ELEGANT_TUXEDO_CHESTPLATE = new SBCustomItem("ELEGANT_TUXEDO_CHESTPLATE", "Elegant Tuxedo Jacket", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(ELEGANT_TUXEDO_CHESTPLATE);
        OLD_DRAGON_CHESTPLATE = new SBCustomItem("OLD_DRAGON_CHESTPLATE", "Old Dragon Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(OLD_DRAGON_CHESTPLATE);
        ZOMBIE_COMMANDER_CHESTPLATE = new SBCustomItem("ZOMBIE_COMMANDER_CHESTPLATE", "Zombie Commander Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(ZOMBIE_COMMANDER_CHESTPLATE);
        PERFECT_CHESTPLATE_2 = new SBCustomItem("PERFECT_CHESTPLATE_2", "Perfect Chestplate - Tier II", "", Material.DIAMOND_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.RARE, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(PERFECT_CHESTPLATE_2);
        STARLIGHT_CHESTPLATE = new SBCustomItem("STARLIGHT_CHESTPLATE", "Starlight Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.RARE, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(STARLIGHT_CHESTPLATE);
        GLACITE_CHESTPLATE = new SBCustomItem("GLACITE_CHESTPLATE", "Glacite Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(GLACITE_CHESTPLATE);
        TARANTULA_CHESTPLATE = new SBCustomItem("TARANTULA_CHESTPLATE", "Tarantula Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(TARANTULA_CHESTPLATE);
        PUMPKIN_CHESTPLATE = new SBCustomItem("PUMPKIN_CHESTPLATE", "Pumpkin Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.COMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(PUMPKIN_CHESTPLATE);
        TANK_MINER_CHESTPLATE = new SBCustomItem("TANK_MINER_CHESTPLATE", "Miner Chestplate", "", Material.DIAMOND_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.RARE, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(TANK_MINER_CHESTPLATE);
        GHAST_CHESTPLATE = new SBCustomItem("GHAST_CHESTPLATE", "Ghast Chestplate", "", Material.CHAINMAIL_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.RARE, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(GHAST_CHESTPLATE);
        REVENANT_CHESTPLATE = new SBCustomItem("REVENANT_CHESTPLATE", "Revenant Chestplate", "", Material.DIAMOND_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(REVENANT_CHESTPLATE);
        PERFECT_CHESTPLATE_9 = new SBCustomItem("PERFECT_CHESTPLATE_9", "Perfect Chestplate - Tier IX", "", Material.DIAMOND_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(PERFECT_CHESTPLATE_9);
        CELESTE_CHESTPLATE = new SBCustomItem("CELESTE_CHESTPLATE", "Celeste Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(CELESTE_CHESTPLATE);
        LAPIS_ARMOR_CHESTPLATE = new SBCustomItem("LAPIS_ARMOR_CHESTPLATE", "Lapis Armor Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(LAPIS_ARMOR_CHESTPLATE);
        SNOW_SUIT_CHESTPLATE = new SBCustomItem("SNOW_SUIT_CHESTPLATE", "Snow Suit Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(SNOW_SUIT_CHESTPLATE);
        SPEEDSTER_CHESTPLATE = new SBCustomItem("SPEEDSTER_CHESTPLATE", "Speedster Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(SPEEDSTER_CHESTPLATE);
        ZOMBIE_KNIGHT_CHESTPLATE = new SBCustomItem("ZOMBIE_KNIGHT_CHESTPLATE", "Zombie Knight Chestplate", "", Material.GOLD_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(ZOMBIE_KNIGHT_CHESTPLATE);
        SPOOKY_CHESTPLATE = new SBCustomItem("SPOOKY_CHESTPLATE", "Spooky Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(SPOOKY_CHESTPLATE);
        SPEED_WITHER_CHESTPLATE = new SBCustomItem("SPEED_WITHER_CHESTPLATE", "Maxor's Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(SPEED_WITHER_CHESTPLATE);
        PROTECTOR_DRAGON_CHESTPLATE = new SBCustomItem("PROTECTOR_DRAGON_CHESTPLATE", "Protector Dragon Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(PROTECTOR_DRAGON_CHESTPLATE);
        GROWTH_CHESTPLATE = new SBCustomItem("GROWTH_CHESTPLATE", "Chestplate of Growth", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.RARE, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(GROWTH_CHESTPLATE);
        FINAL_DESTINATION_CHESTPLATE = new SBCustomItem("FINAL_DESTINATION_CHESTPLATE", "Final Destination Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(FINAL_DESTINATION_CHESTPLATE);
        PERFECT_CHESTPLATE_5 = new SBCustomItem("PERFECT_CHESTPLATE_5", "Perfect Chestplate - Tier V", "", Material.DIAMOND_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(PERFECT_CHESTPLATE_5);
        GUARDIAN_CHESTPLATE = new SBCustomItem("GUARDIAN_CHESTPLATE", "Guardian Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.RARE, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(GUARDIAN_CHESTPLATE);
        EMBER_CHESTPLATE = new SBCustomItem("EMBER_CHESTPLATE", "Ember Chestplate", "", Material.CHAINMAIL_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(EMBER_CHESTPLATE);
        MERCENARY_CHESTPLATE = new SBCustomItem("MERCENARY_CHESTPLATE", "Mercenary Chestplate", "", Material.IRON_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.RARE, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(MERCENARY_CHESTPLATE);
        FARM_SUIT_CHESTPLATE = new SBCustomItem("FARM_SUIT_CHESTPLATE", "Farm Suit Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.COMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(FARM_SUIT_CHESTPLATE);
        FROZEN_BLAZE_CHESTPLATE = new SBCustomItem("FROZEN_BLAZE_CHESTPLATE", "Frozen Blaze Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(FROZEN_BLAZE_CHESTPLATE);
        EMERALD_ARMOR_CHESTPLATE = new SBCustomItem("EMERALD_ARMOR_CHESTPLATE", "Emerald Armor Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(EMERALD_ARMOR_CHESTPLATE);
        METAL_CHESTPLATE = new SBCustomItem("METAL_CHESTPLATE", "Metal Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(METAL_CHESTPLATE);
        REAPER_CHESTPLATE = new SBCustomItem("REAPER_CHESTPLATE", "Reaper Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(REAPER_CHESTPLATE);
        SKELETON_SOLDIER_CHESTPLATE = new SBCustomItem("SKELETON_SOLDIER_CHESTPLATE", "Skeleton Soldier Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(SKELETON_SOLDIER_CHESTPLATE);
        WISE_DRAGON_CHESTPLATE = new SBCustomItem("WISE_DRAGON_CHESTPLATE", "Wise Dragon Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(WISE_DRAGON_CHESTPLATE);
        NECROMANCER_LORD_CHESTPLATE = new SBCustomItem("NECROMANCER_LORD_CHESTPLATE", "Necromancer Lord Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(NECROMANCER_LORD_CHESTPLATE);
        SALMON_CHESTPLATE_NEW = new SBCustomItem("SALMON_CHESTPLATE_NEW", "Salmon Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.RARE, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(SALMON_CHESTPLATE_NEW);
        GENERALS_ARMOR_OF_THE_RESISTANCE_CHESTPLATE = new SBCustomItem("GENERALS_ARMOR_OF_THE_RESISTANCE_CHESTPLATE", "Chestplate of the Rising Sun", "", Material.GOLD_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(GENERALS_ARMOR_OF_THE_RESISTANCE_CHESTPLATE);
        ZOMBIE_CHESTPLATE = new SBCustomItem("ZOMBIE_CHESTPLATE", "Zombie Chestplate", "", Material.DIAMOND_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(ZOMBIE_CHESTPLATE);
        MINER_OUTFIT_CHESTPLATE = new SBCustomItem("MINER_OUTFIT_CHESTPLATE", "Miner's Outfit Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(MINER_OUTFIT_CHESTPLATE);
        EMPEROR_ROBES = new SBCustomItem("EMPEROR_ROBES", "Emperor Robes", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.COMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(EMPEROR_ROBES);
        MUSHROOM_CHESTPLATE = new SBCustomItem("MUSHROOM_CHESTPLATE", "Mushroom Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.COMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(MUSHROOM_CHESTPLATE);
        HEAVY_CHESTPLATE = new SBCustomItem("HEAVY_CHESTPLATE", "Heavy Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.RARE, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(HEAVY_CHESTPLATE);
        BLAZE_CHESTPLATE = new SBCustomItem("BLAZE_CHESTPLATE", "Blaze Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(BLAZE_CHESTPLATE);
        LEAFLET_CHESTPLATE = new SBCustomItem("LEAFLET_CHESTPLATE", "Leaflet Tunic", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.COMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(LEAFLET_CHESTPLATE);
        SHARK_SCALE_CHESTPLATE = new SBCustomItem("SHARK_SCALE_CHESTPLATE", "Shark Scale Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(SHARK_SCALE_CHESTPLATE);
        SHADOW_ASSASSIN_CHESTPLATE = new SBCustomItem("SHADOW_ASSASSIN_CHESTPLATE", "Shadow Assassin Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(SHADOW_ASSASSIN_CHESTPLATE);
        HEAT_CHESTPLATE = new SBCustomItem("HEAT_CHESTPLATE", "Heat Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.RARE, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(HEAT_CHESTPLATE);
        FALLEN_STAR_CHESTPLATE = new SBCustomItem("FALLEN_STAR_CHESTPLATE", "Fallen Star Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.COMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(FALLEN_STAR_CHESTPLATE);
        HYDRA1_CHESTPLATE = new SBCustomItem("HYDRA1_CHESTPLATE", "Water Hydra Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(HYDRA1_CHESTPLATE);
        ADAPTIVE_CHESTPLATE = new SBCustomItem("ADAPTIVE_CHESTPLATE", "Adaptive Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(ADAPTIVE_CHESTPLATE);
        DIVAN_CHESTPLATE = new SBCustomItem("DIVAN_CHESTPLATE", "Chestplate Of Divan", "", Material.GOLD_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(DIVAN_CHESTPLATE);
        DIVER_CHESTPLATE = new SBCustomItem("DIVER_CHESTPLATE", "Diver's Shirt", "", Material.GOLD_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(DIVER_CHESTPLATE);
        ANGLER_CHESTPLATE = new SBCustomItem("ANGLER_CHESTPLATE", "Angler Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.COMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(ANGLER_CHESTPLATE);
        SUPER_HEAVY_CHESTPLATE = new SBCustomItem("SUPER_HEAVY_CHESTPLATE", "Super Heavy Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(SUPER_HEAVY_CHESTPLATE);
        OBSIDIAN_CHESTPLATE = new SBCustomItem("OBSIDIAN_CHESTPLATE", "Obsidian Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(OBSIDIAN_CHESTPLATE);
        PERFECT_CHESTPLATE_8 = new SBCustomItem("PERFECT_CHESTPLATE_8", "Perfect Chestplate - Tier VIII", "", Material.DIAMOND_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(PERFECT_CHESTPLATE_8);
        SALMON_CHESTPLATE = new SBCustomItem("SALMON_CHESTPLATE", "Salmon Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(SALMON_CHESTPLATE);
        MASTIFF_CHESTPLATE = new SBCustomItem("MASTIFF_CHESTPLATE", "Mastiff Chestplate", "", Material.GOLD_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(MASTIFF_CHESTPLATE);
        ROTTEN_CHESTPLATE = new SBCustomItem("ROTTEN_CHESTPLATE", "Rotten Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.RARE, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(ROTTEN_CHESTPLATE);
        SORROW_CHESTPLATE = new SBCustomItem("SORROW_CHESTPLATE", "Sorrow Chestplate", "", Material.CHAINMAIL_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(SORROW_CHESTPLATE);
        FALLEN_STAR_BOOTS = new SBCustomItem("FALLEN_STAR_BOOTS", "Fallen Star Boots", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.COMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(FALLEN_STAR_BOOTS);
        GOLEM_ARMOR_CHESTPLATE = new SBCustomItem("GOLEM_ARMOR_CHESTPLATE", "Golem Armor Chestplate", "", Material.IRON_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.RARE, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(GOLEM_ARMOR_CHESTPLATE);
        SPONGE_CHESTPLATE = new SBCustomItem("SPONGE_CHESTPLATE", "Sponge Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(SPONGE_CHESTPLATE);
        STARRED_ADAPTIVE_CHESTPLATE = new SBCustomItem("STARRED_ADAPTIVE_CHESTPLATE", "Adaptive Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(STARRED_ADAPTIVE_CHESTPLATE);
        FLAME_BREAKER_CHESTPLATE = new SBCustomItem("FLAME_BREAKER_CHESTPLATE", "Flamebreaker Chestplate", "", Material.CHAINMAIL_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(FLAME_BREAKER_CHESTPLATE);
        SQUIRE_CHESTPLATE = new SBCustomItem("SQUIRE_CHESTPLATE", "Squire Chestplate", "", Material.IRON_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.UNCOMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(SQUIRE_CHESTPLATE);
        ARMOR_OF_MAGMA_CHESTPLATE = new SBCustomItem("ARMOR_OF_MAGMA_CHESTPLATE", "Armor of Magma Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(ARMOR_OF_MAGMA_CHESTPLATE);
        END_CHESTPLATE = new SBCustomItem("END_CHESTPLATE", "Ender Chestplate", "", Material.CHAINMAIL_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(END_CHESTPLATE);
        PERFECT_CHESTPLATE_10 = new SBCustomItem("PERFECT_CHESTPLATE_10", "Perfect Chestplate - Tier X", "", Material.DIAMOND_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(PERFECT_CHESTPLATE_10);
        TITAN_CHESTPLATE = new SBCustomItem("TITAN_CHESTPLATE", "Titan's Chestplate", "", Material.DIAMOND_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(TITAN_CHESTPLATE);
        PERFECT_CHESTPLATE_11 = new SBCustomItem("PERFECT_CHESTPLATE_11", "Perfect Chestplate - Tier XI", "", Material.DIAMOND_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(PERFECT_CHESTPLATE_11);
        ZOMBIE_LORD_CHESTPLATE = new SBCustomItem("ZOMBIE_LORD_CHESTPLATE", "Zombie Lord Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(ZOMBIE_LORD_CHESTPLATE);
        MINERAL_CHESTPLATE = new SBCustomItem("MINERAL_CHESTPLATE", "Mineral Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(MINERAL_CHESTPLATE);
        PERFECT_CHESTPLATE_12 = new SBCustomItem("PERFECT_CHESTPLATE_12", "Perfect Chestplate - Tier XII", "", Material.DIAMOND_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(PERFECT_CHESTPLATE_12);
        FANCY_TUXEDO_CHESTPLATE = new SBCustomItem("FANCY_TUXEDO_CHESTPLATE", "Fancy Tuxedo Jacket", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(FANCY_TUXEDO_CHESTPLATE);
        PERFECT_CHESTPLATE_6 = new SBCustomItem("PERFECT_CHESTPLATE_6", "Perfect Chestplate - Tier VI", "", Material.DIAMOND_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(PERFECT_CHESTPLATE_6);
        PERFECT_CHESTPLATE_1 = new SBCustomItem("PERFECT_CHESTPLATE_1", "Perfect Chestplate - Tier I", "", Material.DIAMOND_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.RARE, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(PERFECT_CHESTPLATE_1);
        CRYPT_WITHERLORD_CHESTPLATE = new SBCustomItem("CRYPT_WITHERLORD_CHESTPLATE", "Crypt Witherlord Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(CRYPT_WITHERLORD_CHESTPLATE);
        FALLEN_STAR_LEGGINGS = new SBCustomItem("FALLEN_STAR_LEGGINGS", "Fallen Star Leggings", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.COMMON, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(FALLEN_STAR_LEGGINGS);
        WISE_WITHER_CHESTPLATE = new SBCustomItem("WISE_WITHER_CHESTPLATE", "Storm's Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(WISE_WITHER_CHESTPLATE);
        PERFECT_CHESTPLATE_4 = new SBCustomItem("PERFECT_CHESTPLATE_4", "Perfect Chestplate - Tier IV", "", Material.DIAMOND_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(PERFECT_CHESTPLATE_4);
        STRONG_DRAGON_CHESTPLATE = new SBCustomItem("STRONG_DRAGON_CHESTPLATE", "Strong Dragon Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(STRONG_DRAGON_CHESTPLATE);
        ARMOR_OF_THE_RESISTANCE_CHESTPLATE = new SBCustomItem("ARMOR_OF_THE_RESISTANCE_CHESTPLATE", "Chestplate of the Rising Sun", "", Material.GOLD_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(ARMOR_OF_THE_RESISTANCE_CHESTPLATE);
        STARRED_SHADOW_ASSASSIN_CHESTPLATE = new SBCustomItem("STARRED_SHADOW_ASSASSIN_CHESTPLATE", "Shadow Assassin Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.LEGENDARY, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(STARRED_SHADOW_ASSASSIN_CHESTPLATE);
        ZOMBIE_SOLDIER_CHESTPLATE = new SBCustomItem("ZOMBIE_SOLDIER_CHESTPLATE", "Zombie Soldier Chestplate", "", Material.LEATHER_CHESTPLATE, (short) 0, "", SBCustomItem.Rarity.EPIC, false, SBCustomItem.Category.CHESTPLATE, skyBlock);
        SBItems.registerItem(ZOMBIE_SOLDIER_CHESTPLATE);


    }

}

